### ISSUE TITLE
Migrate all sector_id columne types to bigint

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel-visor#107]
### Problem
Currently sector_id columns are type `bigserial`. This because go-pg uses bigserial when a bigint is part of a primary key. See [go-pg/pg@v10.3.1/orm/table_create.go#L144](https://github.com/go-pg/pg/blob/v10.3.1/orm/table_create.go#L144) and the pkSQLType function.

### Acceptance Criteria
- All `sector_id` columns are migrated to `bigint`.

**Comment by iand** [comment]
Done as part of the schema overhaul in https://github.com/filecoin-project/sentinel-visor/pull/111
