### ISSUE TITLE
Capture Prometheus metrics exposed by Visor

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel-visor#109]
Visor exports Prometheus metrics via opencensus. Users of visor need a means of collecting and viewing these metrics for monitoring. Gut reaction is to use drone's Prometheus plugin to ingest the metrics into timescale, but open to alternatives.

**Comment by lanzafame** [comment]
Quoting @iand 
> Use prom operator to auto collect in k8s

**Comment by placer14** [comment]
Thought about standing up a prom service within docker-compoes for dev purposes. And let k8s handle the the prod scenario.

**Comment by frrist** [comment]
This issue has rotted, closing.
