### ISSUE TITLE
visor_processing_stats table should have the actor as a separate column

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/sentinel-visor#120]
When querying a postgres datasource in grafana, you can treat certain columns as the metric and some as the value, i.e.
```sql
select recorded_at as "time", 
    actor as "metric",
    value
from visor_processing_stats
where measure = 'actors_incomplete_height_max';
```
This would then plot all the `incomplete_height_max` values by each actor on a single graph. Currently, the query looks like the following:
```sql
select recorded_at as "time",'
    measure,
    value 
from visor_processing_stats 
where measure ~ 'actor_*'
```

Which looks like the following
<img width="2130" alt="Screen Shot 2020-10-19 at 12 32 50" src="https://user-images.githubusercontent.com/5924712/96395169-3fd61d80-1207-11eb-8a94-687610b55700.png">

And it provides no simple way to distinguish the different actor metrics.

**Comment by iand** [comment]
We can add that column. It would be empty for half the stats (tipset and messages) and we would need to change the primary key to cover the actor column too. I kept the table design simple and I wouldn't want to keep adding columns for extra dimensions in the future. If we were to do it then it might be worth generalising it to include the tipset and message variants: `statechange`, `economics`, `message` and `gas outputs`. Maybe call the column `task_key` indicating that it's a key that specialises the measure: could be an actor code or a task type.

On a side note, I don't find that particular graph to be usable. I've been using the stats like this:

![Screenshot from 2020-10-19 13-05-30](https://user-images.githubusercontent.com/18375/96448769-cb51ad80-120b-11eb-9b27-7070d0409ad4.png)

**Comment by lanzafame** [comment]
The reason I want to look at all the actor state stats together is that it represents the work of a single visor task worker set, i.e. `visor run --actorstate-workers=5` <- this set of workers are what is working to increment that set of stats
