### ISSUE TITLE
Capture process for manually migrating ephemerial data in upcoming release

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#124]
The upcoming release has many migrations which optimize the schema for both realtime monitoring as well as deep analysis. These migrations are both expensive to apply on already captured data (persisted in database) and costly to manage while the system remains in use for realtime monitoring purposes. We will document a manual migration process to assist those running visor in production while allowing those which don't have large databases to apply migrations if realtime monitoring and performance are not a requirement for your deployment. Part of that documentation requires the non-reproduceable data to be migrated manually. This issue will describe the steps needed to manually migrate this non-reproduceable data in a way which supports deployments which require realtime monitoring to be maintained for already-large databases.

To do:
- [x] Identify non-reproduceable data which require manual migration
- [ ] prepare migration instructions
- [ ] document proper execution of migration in a live production environment
- [ ] test migration plan against live production-like database

**Comment by placer14** [comment]
Non reproduceable data exists in the following tables:
- chain_block
- chain_mpool (needs migration applied from https://github.com/filecoin-project/sentinel-drone/pull/34)
- chain_tipset
- all lotus* tables

**Comment by frrist** [comment]
This issue has rotted, closing.
