### ISSUE TITLE
Separate high confidence indexing from low-confidence

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#127]
To ensure we capture early evidence of potential forks we need to run the head indexer with a low or zero confidence. However this results in reverted tipsets being indexed and bloats the database tables and also complicates heaviest chain analyses.

Separate the head indexer into two parts: 

 - high confidence with a tipset cache writing to the existing processing tables
 - bleeding edge indexing every seen tipset and block to new processing tables (potentially with limited data retention)

**Comment by placer14** [comment]
Resolving indirectly via separate monitoring/analysis deployments taking these requirements into account.
