### ISSUE TITLE
maintain mapping of `tipset` -> children `tipsets`

### ISSUE THREAD

**Issue by willscott** [filecoin-project/sentinel-visor#129]
currently, we can get the parent state root of a tipset, but not the resulting state of all messages applied.

This is only stored in the next blocks building on that tipset as their `parentStateRoot`. We will find this mapping useful in several points of analysis.

Given a tipset {A,B,C} we would include all children (assuming two: {D,E} and {D,E,F}) which point to this set, the result would be:
{A,B,C} -> {D,E}
{A,B,C} -> {D,E,F}

**Comment by willscott** [comment]
message parsing sometimes fails due to this:
`process tipset: extract message models: get actor: resolution lookup failed (f3ss7ach3j422b5mzjsbzmx64uxhpqy5fjz5nvpomvreymvrutwmptsfhke6o4eaqoaurnm22zt42qcam36lcq): resolve address f3ss7ach3j422b5mzjsbzmx64uxhpqy5fjz5nvpomvreymvrutwmptsfhke6o4eaqoaurnm22zt42qcam36lcq: actor not found`

we should be computing on the result of the tipset, not the parentStateRoot to find the actor

**Comment by frrist** [comment]
> we should be computing on the result of the tipset, not the parentStateRoot to find the actor

This is only for the case where we are performing message parsing with the statediff library, corect?

**Comment by willscott** [comment]
that's where we're currently running into it at the moment, yes

**Comment by placer14** [comment]
This has some concerns with Lotus API semantics on which tipset and which state root is used around these endpoints. Table for discussion later.

**Comment by hsanjuan** [comment]
We can probably discuss this again as Lotus has upgraded the semantics?

**Comment by frrist** [comment]
Yes, this was leftover from before the lotus API was consistent around states.
