### ISSUE TITLE
Argument `--to` and `--from` not respected for historical tipset indexing

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#142]
Ran the following visor command intending to capture from 178800 and prior tipsets but found tipset past 178800 in the `visor_processing_tipsets` table.

Should apply to all indexing and processing except `indexhead`.

`./visor --repo=/lotus-data/.lotus --db-pool-size=15 --log-level=info run --indexhead=false --to 178800 --scb 50 --scw 5 --asb 50 --asw 5 --mb 50 --mw 5 --gob 50 --gow 5 --ceb 50 --cew 5 --indexhistory=true`

**Comment by iand** [comment]
`--to` only applies to actor and message processing tasks: `"Limit actor and message processing to tipsets at or below HEIGHT"`

We could make the history indexer respect it for writing to the database. It probable would still have to start higher than the `--to` value and walk backwards unless there is a way to get the tipset for an epoch via the API

**Comment by frrist** [comment]
@iand has a fix for this in #221
