### ISSUE TITLE
Track Miner Actor State Changes

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel-visor#145]
### Motivation & Background
We need to track Miner State Information. There are static and dynamic parts of the miner state:

**Static Info:**
  - MinerID
  - SectorSize
  - WindowPoStPartitionSectors

**Dynamic Info:** (excluding complex fields represented by a CID, e.g. PreCommitSecotrs, VestingFunds, Sectors, AllocatedSectors, etc.)
  - Owner, Worker, and ControlAddresses
  - PeerID, MultiAddrs
  - ConsensusFaultElapsed
  - PreCommitDeposits
  - LockedFunds
  - FeeDebt
  - InitialPledge
  - CurrentDeadline

The `Owner`, `Worker`, `Control addresses`, `PeerID`, `MultiAddrs`, and `ConsesnsuFaultsElapsed` are contained in the [MinerInfo field](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/miner_state.go#L81) and changes to these values can be detected by inspecting the [MinerInfo CID](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/miner_state.go#L32) for changes across state changes.

The `PreCommitDeposits`, `LockedFunds`, `FeeDebt`, `InitialPledge`, and `CurrentDeadline` fields are contained in the Miner State structure and changes to these values can be detected by inspecting the fields at the previous state.

### Acceptance Criteria
We need to persist these values when they change for analysis and tracking. Currently there are `miner_state` and `miner_info` tables that do not take the dynamic vs. static nature of the miner actor state into account, its probably simplest to remove these and start fresh but this is left to the implementer. The below table names are _suggestions_, naming is hard.

- Record miner static info to a table. `miner_static_info`
- Record dynamic fields contained in MinerInfo structure to a table along with the `StateRoot` and `MinerID` `miner_dynamic_info`
- Record the dynamic fields contained in the MinerState structure to a table along with the `StateRoot` and `MinerID` `miner_dynamic_state`

**Comment by placer14** [comment]
Thoughts:
- Instead of dynamic/static as a means of describing the lifetime of the data, let's instead talk about them in terms of how they are persisted/used in the schema. So, something like `miner_current_state`/`miner_state_latest` vs `miner_states`.
- `ConsensusFaultElapsed` appears to be dynamic, not static. It might make sense to include in the `latest` or `current` state table even though it's changing often (every time the miner faults, in this case). The decision should fall on how expensive it is to update versus insert a new row.
- `InitialPledge` I _think_ is not going to change per storageminer?

**Comment by frrist** [comment]
Perhaps `miner_current_state` could just be a view we update with the most recent values from `miner_state_latest`?

> ConsensusFaultElapsed appears to be dynamic, not static

Right, I believe this is stated in `Background & Motivation`. I think we should only insert it, meaning we always append to the `miner_state_latest` table.

> InitialPledge I think is not going to change per storageminer?

`InitialPledge` is the sum of initial pledge requirements of all active sectors, meaning it will change when a new sector is added and when a sector is removed either for early termination or expiration.

**Comment by frrist** [comment]
Another point I'd like to add. Since `PreCommitDeposits`, `LockedFunds`, `FeeDebt`, `InitialPledge`, `CurrentDeadline`, and `ConsesnsuFaultsElapsed` all change independently of each other and since some fields were added in specs-actorsv2 and do not exists in v1 it might make more sense to give them each their own tables.

**Comment by frrist** [comment]
closed via #158
