### ISSUE TITLE
[Discuss] Support file based configuration 

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel-visor#147]
### Motivation & Background
Visor currently accepts a wide array of command line flags to tune its processing and performance. As we continue to build out visor this list of arguments is likely to grow. Due to this we should add support for file based configuration s.t. visor can be passed a file specifying its processing and performance options.  This issue serves as a medium for discussion.

### Acceptance Criteria
- In discussion or via (:+1:/:-1:) we decide if this is a feature we want.
- A file format is chosen, .json, .toml, .yaml, etc.
- This issue is either repurposed or a new issue is created to track the work of adding this feature.

**Comment by iand** [comment]
The approach here will be influenced by whether we keep visor as a single monolithic application or it is decomposed into independent tasks.

**Comment by placer14** [comment]
Seems reasonable to pursue. Allow CLI framework to decide which format to us. Prioritzation next.

**Comment by frrist** [comment]
The CLI library used by Visor supports file based configuration via: https://github.com/urfave/cli/blob/master/docs/v2/manual.md#values-from-alternate-input-sources-yaml-toml-and-others

**Comment by frrist** [comment]
Conversation with some users indicate this is not currently a pain point, keeping in the backlog until it hurts.
