### ISSUE TITLE
database I/O timeout

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#153]
Detecting this error pretty regularly when database is under heavy use:
```
2020-10-27T14:34:33.454Z        ERROR   actorstate      actorstate/actorstate.go:261    failed to mark actor complete   {"actor_head": "bafy2bzacecwuuwl5vnnyuxksk7m47w3jelq5wj3f35snrf56lctlt5wi3kwqy", "actor_code": "bafkqadlgnfwc6mrpmfrwg33vnz2a", "tipset": "{bafy2bzacedn
hrk2kn6xtr5a5cwnxega6vorlvnuwlpmzlovpohxknxde2hd5i,bafy2bzaced2g4ydr6oif3cbq4o3w4dvhwtc3udo2vtjaefi4purym2mg45xpi,bafy2bzacechzowhkriecwhvuflijphbnz5nwo5u4ilp6qek6s6fqpd7w7qtre}", "error": "read tcp 172.31.13.244:49356->3.90.201.255:13574: i/o timeout"}
```

Unsure if this a server timeout or a client timeout. If the latter, it might be sufficient to just allow for configurable timeout with a large default on the client side. If the former, hoping a simple config could improve this.

**Comment by frrist** [comment]
@ian states that one reason this could have happened is due to long queries holding onto connections from the pool, unconfirmed.

@placer14 has seen this recently and will add related data.

**Comment by placer14** [comment]
Apologies. I've looked at logs and don't see any recent occurrances as I suspected. Recommending we close until/if we encounter this again.

**Comment by placer14** [comment]
The issues started to reappear around Nov 13th, 18:00 UTC. This approximately coincides with upgrading lotus fullnodes in that environment to v1.1.3. Logs: https://gist.github.com/placer14/33186e50d164c8ed64e18072ce0d01ad

**Comment by frrist** [comment]
```
"2020-11-17T22:12:07.329Z\t\u001b[31mERROR\u001b[0m\tschedule\tschedule/scheduler.go:143\ttask exited with failure\t{\"task\": \"ChainHeadIndexer\", \"error\": \"open lens: new full node rpc: dial tcp 172.20.188.234:1234: i/o timeout\"}
```
I don't thing this is a database timeout, `172.20.188.234:1234` looks like a lotus node

**Comment by placer14** [comment]
Ah, yes. Confused issues. Thanks.

**Comment by placer14** [comment]
Note: Removed comment continaing extraneous logs.
