### ISSUE TITLE
Define Extractor for Multisig Actor

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#154]
### Motivation & Background
To analyze and monitor token flows we need to extract multisig actor states. This will require adding a new extractor for the multistage actor type and defining new models for the extracted data.

### Acceptance criteria
Extract the following fields from the Multisig Actor state:
- Signers: a slice of addresses, model as json, dynamic value.
- NumApprovalsThreshold: number of approvals required to execute a transaction, model as uint64, dynamic value
- NextTxnID: Next ID that a transaction will be assigned to when added to the `PendingTxns` HAMT, model as uint64, dynamic value.
- InitialBalance: The token balance locked in the multisig actor, model as string,  dynamic value.
- StartEpoch: Epoch vesting begins, model as int64, dynamic value.
- UnlockDuration: Duration of vesting, model as int64, dynamic value.
- PendingTxns: HAMT mapping transactions ID's to corresponding Transactions, requires separate table,  dynamic value.

Transactions will need to be extracted from the PendingTxns HAMT, the fields of a Multisig Transaction include:
- To: address message will be sent to, model as string, static value.
- Value: value of message, model as string, static value.
- Method: method to call on `To`, model as int64, static value.
- Params: params of message, model as bytes, static value.
- Approved: Slice of addresses that have approved transaction, model as json, dynamic value

Note: The params of the Transaction could be parsed using the statediff tool (@willscott can you confirm this?)

### Where to begin
Multisig actor state: https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_state.go#L14-L29)
Lotus Interface Shim: https://github.com/filecoin-project/lotus/blob/master/chain/actors/builtin/multisig/state.go#L39

**Comment by frrist** [comment]
Currently we don't have extractors defined for the Multisig and Account Actors so this behavior is expected.

**Comment by placer14** [comment]
Re: Multisig state (https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_state.go#L14-L29)

Toward identifying potential scope, we probably want to capture the following at first glance:
- Signers length int
- NumApprovalsThreshold int
- NextTxnID (assume this is an CID?) string
- InitialBalance string
- StartEpoch int
- UnlockDuration int
- PendingTxns CID string

**Comment by placer14** [comment]
Actually, it looks like we do have some of these actor states already? Maybe these are the v1 Multisig actors?
```
head	code	state	height
bafy2bzaceaee4e3cywidkn2w6hps36svs7zy3ms43rmfmyr7egrayklormtig	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 24, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""2233759725896110000000"", ""UnlockDuration"": 2102400, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzaceaegl2vis7wac342livzyyx7nv4gcduqqvt6gpei2g5bftg6nn6se	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 10, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""173973760300000000000"", ""UnlockDuration"": 525600, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzaceapfirkteqkqhkwfexbd2nbzcg7lltg242troha7idu4keid5iw2s	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 24, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""17263238095238000000000"", ""UnlockDuration"": 3153600, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzaceaxhb7wqe7xlqcn2atgwl23y4i75ftkfoydq2xqlv62gryvlf24uu	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 24, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""4184460000000000000000"", ""UnlockDuration"": 525600, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzacebba2d4aeoct74vhdlf72a3uwpfs2gmlumfjco6xyqniht57tgjfc	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 25, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""4646591411250000000000"", ""UnlockDuration"": 2102400, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzacebjc2uhszq5x4hd7wp6aimmi3w6pciiiudocmwhpm4qiss5w6uab2	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 14, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""2458968203780000000000"", ""UnlockDuration"": 3153600, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzacec7mnitvgzlh5lkfzfnwr5enrrj5ki3szbi7oqohnmok2vh3dfrxy	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 24, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""1140380000000000000000"", ""UnlockDuration"": 525600, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzacedip7bv2qriu6nsw72ddqtuwjqf6hnitgn7o2vsagawnpi2gqajda	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 14, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""856735678410000000000"", ""UnlockDuration"": 1051200, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzacediwmza3t52riy4azd2bspvrjeueexy54u6mipozxalh3jggs2pwm	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 24, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""378989200000000000000000"", ""UnlockDuration"": 3153600, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzacedjrpvgwldkukvszoj4pose4xxan7sjhlh2ght5ly6syolvrdw36y	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 24, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""1139218029816030000000"", ""UnlockDuration"": 525600, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzacedobnlfu55yd66v2uueyzetymqrcokunmlnxcnprbjvxldjlqofii	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 25, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""33060430003703100000000"", ""UnlockDuration"": 3153600, ""NumApprovalsThreshold"": 1}"	161280
bafy2bzacedzs2qepzeqj2togs2puun4xtftu7gzsegaxaqzlbctu7kox44ngk	bafkqadtgnfwc6mrpnv2wy5djonuwo	"{""Signers"": [""f023933""], ""NextTxnID"": 24, ""StartEpoch"": 148888, ""PendingTxns"": {""/"": ""bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay""}, ""InitialBalance"": ""6157932935761020000000"", ""UnlockDuration"": 1051200, ""NumApprovalsThreshold"": 1}"	161280
```

Instead of inflating a new table for this data, it should be enough to just add v2 states into `actor_states` just like these. We can use JSON operators to query on these if needed in the short term.

**Comment by frrist** [comment]
I suspect the PendingTxns HAMT will need to be deserialized to fully track token flow, I've updated the issues description with some details on this.

**Comment by placer14** [comment]
Discussion around pattern for new tasks occurred which might influence how we deliver this work. I will write up an issue outlining the pattern for discussion and reference here.

**Comment by frrist** [comment]
@willscott, @placer14  mentioned completing this issues may collide with your work in https://github.com/filecoin-project/sentinel-visor/issues/169. I suspect we can work on these in parallel but figured I should check with you before starting.
