### ISSUE TITLE
[CI] Block PRs from merging that have dirty modules

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel-visor#170]
### Description
PRs that have not had `go mod tidy` ran against them should be blocked from merging.  

### Acceptance criteria
- Add a step to CI that prevents PRs from merging if their modules are dirty

### Where to begin
Prior art in [lotus](https://github.com/filecoin-project/lotus/blob/master/.circleci/config.yml#L77) and [specs-actors](https://github.com/filecoin-project/specs-actors/blob/master/.circleci/config.yml#L32)

**Comment by iand** [comment]
This is failing on newer versions of Go. I'm on go tip and `go mod tidy` is clean for me but fails the CI check. I haven't investigated in depth but I saw that the check is using Go 1.13 so perhaps that is the cause.

**Comment by frrist** [comment]
I'm on `go1.15.5` and `go mody tidy` is dirty for me:
```
frrist@sequoia:~/s/g/f/sentinel-visor|frrist/fix-go-mod-tidy-ci✓
➤ git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```
```
frrist@sequoia:~/s/g/f/sentinel-visor|master✓
➤ git pull origin master
```
```
From github.com:filecoin-project/sentinel-visor
 * branch            master     -> FETCH_HEAD
Already up to date.
```
```
frrist@sequoia:~/s/g/f/sentinel-visor|master✓
➤ go version
go version go1.15.5 linux/amd64
```
```
frrist@sequoia:~/s/g/f/sentinel-visor|master✓
➤ go mod tidy
```
```
frrist@sequoia:~/s/g/f/sentinel-visor|master⚡*
➤ git ls
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   go.sum

no changes added to commit (use "git add" and/or "git commit -a")
```

I'm not sure what's wrong here...

**Comment by frrist** [comment]
we do this
