### ISSUE TITLE
cbor decode error: Invalid majorByte: 0xf1

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#177]
### Describe the bug:
`{"error": "process tipset: extract message models: parse message bafy2bzacea7wl3e5yiacadpzewyw3g3cqerdolahu7gkuo545qlbcu6hsapas failed: parse params: cbor decode into Unknown (unknown.0) failed: Invalid majorByte: 0xf1", "height": 162886}`

### Steps to Reproduce:
Running visor with `--dpm=true` and parsing the above message CID.

**Comment by willscott** [comment]
it looks like the parameters for that message are invalid cbor

https://decentralized.app/cid?cid=bafy2bzacea7wl3e5yiacadpzewyw3g3cqerdolahu7gkuo545qlbcu6hsapas&as=unknown

the bytes of the params (in hex) are
`f13655f57baf6a8b194a7743b000b23abae7478fbb7889255c7041f296f286c75bd72601611d7d3ee7ad1d7dd5da8c27f1a10d472d2d8aa5efeff2ed794c007201`
which doesn't decode to valid cbor.
