### ISSUE TITLE
Optimize actor work leasing

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#188]
### Description

Leasing work for actor processing is too slow, probably due to contention on visor_processing_actors. 

### Acceptance criteria

 * Leasing a batch of rows for actor processing and recording processing completion for each row should take under 5% of the time needed to process the batch, assuming up to 20 concurrent visor instances each with 20 workers.

### Where to begin

Current query statistics

Calls: 4141
Min:  169905.2ms
Max: 403585.4ms
Mean: 237153.5ms

```sql
WITH leased AS ( UPDATE visor_processing_actors a SET claimed_until = $1 FROM ( SELECT * FROM visor_processing_actors WHERE completed_at IS null AND (claimed_until IS null OR claimed_until < $2) AND height >= $3 AND height <= $4 AND code IN ($5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ORDER BY height DESC LIMIT $15 FOR UPDATE SKIP LOCKED ) candidates WHERE a.head = candidates.head AND a.code = candidates.code RETURNING a.head, a.code, a.nonce, a.balance, a.address, a.parent_state_root, a.tip_set, a.parent_tip_set, a.height) SELECT head, code, nonce, balance, address, parent_state_root, tip_set, parent_tip_set, height from leased
```

Adding height into the update clause improves performance 10x (from https://github.com/filecoin-project/sentinel-visor/commit/512161a53a35ad5ec80405e46ef4fcbe50a1a453)

Calls: 138457
Min: 2040.8
Max: 56886.6
Mean: 19579.7

```sql
WITH leased AS ( UPDATE visor_processing_actors a SET claimed_until = $1 FROM ( SELECT * FROM visor_processing_actors WHERE completed_at IS null AND (claimed_until IS null OR claimed_until < $2) AND height >= $3 AND height <= $4 AND code IN ($5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ORDER BY height DESC LIMIT $15 FOR UPDATE SKIP LOCKED ) candidates WHERE a.head = candidates.head AND a.code = candidates.code AND a.height >= $16 AND a.height <= $17 RETURNING a.head, a.code, a.nonce, a.balance, a.address, a.parent_state_root, a.tip_set, a.parent_tip_set, a.height) SELECT head, code, nonce, balance, address, parent_state_root, tip_set, parent_tip_set, height from leased
```

**Comment by iand** [comment]
Also the updating of completed work has a high variation. It's not possible to tell if this was improved with the height changes in https://github.com/filecoin-project/sentinel-visor/commit/512161a53a35ad5ec80405e46ef4fcbe50a1a453 without resetting statistics

No other processing table update appears in the query statistics.

Calls: 2368939
Min: 19.4
Max: 282812.6
Mean: 16039.3

```sql
UPDATE visor_processing_actors SET claimed_until = $1, completed_at = $2, errors_detected = $3 WHERE head = $4 AND code = $5
```
This could possibly be improved by including height in the WHERE clause

**Comment by frrist** [comment]
@placer14 will create an epic to track this work.

**Comment by iand** [comment]
We're not using leasing in this way any more
