### ISSUE TITLE
Optimize visor processing stats collection

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#191]
### Description

Inserting statistics into visor_processing_stats takes too long (>10 minutes). This is probably due to very slow select count(*) queries over processing hypertables.

### Acceptance criteria

 * Writing stats into visor_processing_stats should take < 5s

### Where to begin

Current query takes ~699999.4ms

**Comment by frrist** [comment]
I believe this is addressed based on the metrics we are seeing for insertion times on said table.
