### ISSUE TITLE
Make StateGetActor consistent and performant.

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel-visor#196]
### Description
Calls to the lotus API method `StateGetActor` perform the following actions:
- Executes all messages in a TipSet.
- Returns the Actor State after TipSet message execution -- it computes state.

Both of these out comes are undesirable, computing state from TipSet messages is expensive and returning actor state after message execution is inconsistent with the other lotus API methods (described in greater detail here https://github.com/filecoin-project/lotus/pull/4545)

Until Lotus fixes this Visor needs to "do the right thing", meaning it should not run state computation logic when `StateGetActor` is called and instead should use the TipSet's parent state when getting actor states. 

Lastly an issue will need to be filed to track the removal of this logic when Lotus fixes their stuff.

### Acceptance criteria
- [x] re-implement `StateGetActor` as follows:
https://github.com/filecoin-project/sentinel-visor/blob/43a713c20b666644686e75a67434f50e77764589/tasks/message/message.go#L331-L337 
- [x] Call the new method in all Visor Lens implementations:
  - [ ] APILens
  - [ ] RepoLens
  - [ ] SqlLens
  - [ ] Carrepo
- [x] File issue to track removal of this temporary logic (when https://github.com/filecoin-project/lotus/pull/4545 lands I assume) and reference it in changes to the aforementioned lenses. 

### Where to begin
https://github.com/filecoin-project/sentinel-visor/tree/master/lens

**Comment by hsanjuan** [comment]
Shouldn't we be introducing some in-mem caching so that LoadStateTree becomes a no-op too? I am not sure how cheap it is, but calling it for every actor in the state doesn't sound optimal.

**Comment by hsanjuan** [comment]
@frrist I filed #405. Re-open if I missed something here.
