### ISSUE TITLE
Goroutine leak

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/sentinel-visor#206]
### Describe the bug:
In the latest few releases I have noticed that visor is leaking goroutines, not horrendously but the number of goroutines creeps up.
<img width="1176" alt="Screen Shot 2020-11-05 at 10 32 18" src="https://user-images.githubusercontent.com/5924712/98196227-56060c80-1f6f-11eb-8032-1076f2530d01.png">

**Comment by iand** [comment]
Only spent a few minutes looking at the stack trace but I suspect we're not closing the jsonrpc connection to the api properly in the new reconnection logic. There are 91 goroutines similar to this in long standing selects:

```
1: select [349 minutes] [Created by go-jsonrpc.(*client).makeOutChan.func1 @ client.go:307]
    reflect    select.go:566 rselect([]runtimeSelect(0xc00507bd50 len=3 cap=4), 0x24a8b9d, 0xe)
    reflect    value.go:2250 Select([]SelectCase(#1 len=3 cap=4), 0x2, 0x3, #1, 0x2, 0x4)
    go-jsonrpc client.go:332 (*client).makeOutChan.func1.1(*client(0x2925ee0), Context(0xc007386450), Type(0x2044640), 18)
```

And 94 like this:

```
1: chan receive [207 minutes] [Created by go-jsonrpc.(*wsConn).handleResponse @ websocket.go:369]
    go-jsonrpc websocket.go:282 (*wsConn).handleCtxAsync(*wsConn(0xc007bd46c0), Context(0x2925ee0), 1)
```



[visor-206-goroutine-leak-lanzafame-stack-pp.txt](https://github.com/filecoin-project/sentinel-visor/files/5493575/visor-206-goroutine-leak-lanzafame-stack-pp.txt)

**Comment by placer14** [comment]
The scheduling has changed aorund this. Closing until evidence of this issue reemerges.
