### ISSUE TITLE
"Lock not acquired" should be fatal

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#207]
When the `ChainHeadIndexer` hits the case of [not acquring its lock](https://github.com/filecoin-project/sentinel-visor/issues/51), the task should cause visor to fatally die instead of accept that it cannot start without further action.

**Comment by hsanjuan** [comment]
When I checked, if ChainHeadIndexer is the only task, visor does stop. I took this to mean that we want visor to stop even if this is not the only task running. Or is it more subtle and what we want is a non-0 return error?

**Comment by placer14** [comment]
@hsanjuan The problem is that when the indexer fails, it never retries without manually restarting the process (as the retry logic isn't attempted). The purpose of this failure is to allow kubernetes to restore the process when it is not nominal. I don't believe the exit code is considered when deciding to restart the service, so this should be alright. Thank you!

**Comment by placer14** [comment]
Looking at the current state of things, we aren't suffering from lock acquisition problems since the delivery of https://github.com/filecoin-project/sentinel-visor/pull/149. Deciding against applying this hack and will keep an eye out for the locking problems should they regress again.
