### ISSUE TITLE
Tweak existing caches to explore improving badger access

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#211]
### Description
Observations that we are conuming badger excessively. This issue to consider tweaking our existing caches to optimize our access patterns today (noticing that there are architecture design changes to be made which would further improve performance here but is outside the scope of this issue).

### Acceptance Criteria
- [ ] represent improvement of the speed due to caching tweaks before/after benchmarking.

**Comment by frrist** [comment]
Also worth noting that the lotus people are working to improve the lotus datastore and could make this work obsolete

**Comment by hsanjuan** [comment]
I think we increased cache values. Are we happy? Is this obsolete now given new approaches and upcoming and past improvements in Lotus?
