### ISSUE TITLE
Document visor schema

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#223]
### Description

Reduce the barrier to understanding how to use the database by documenting the schema.

### Acceptance criteria
 
 - Each table, view and column has a description that details its purpose and source
 - Descriptions are queryable and accessible by tools using the database
 - Documentation is automatable

### Where to begin

 - Postgres allows `COMMENT`s to be applied to most objects. These form part of the schema and are queryable. 
 - Possibly extend go-pg to generate the COMMENT based on annotations on the model type.

**Comment by alanshaw** [comment]
I would like to help with this endeavour!

**Comment by olizilla** [comment]
It's a little out of date, but this what we have currently: https://github.com/filecoin-project/sentinel/blob/master/docs/sentinel_tables_purpose.csv

**Comment by PatrickDeuse** [comment]
https://www.postgresql.org/docs/12/sql-comment.html as reference
