### ISSUE TITLE
Chain powers are not extracted

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#224]
### Describe the bug:

The chain_powers table is empty after running the storage power actor extractor. I didn't see any errors during the backfill which covered 31881 actor states. The power_actor_claims table which is written by the same task does have data in it.  

(see https://protocollabs.slack.com/archives/CT2265RFZ/p1604926790480700?thread_ts=1604921495.478300&cid=CT2265RFZ for a tiny amount of context)

### Visor Version

visor-v0.2.0+72-ge1942a5-dirty (iand/beefy branch)

This commit: https://github.com/filecoin-project/sentinel-visor/pull/221/commits/64d05f2a20119b5e7e3781966cdc486cd552352f

**Comment by frrist** [comment]
Most recent changes to the code path were made in https://github.com/filecoin-project/sentinel-visor/pull/172.

Until this is resolved the values can be extracted from `actor_states`.

**Comment by iand** [comment]
For comparison, 

```
sentinel-analysis=> select * from visorstats.power_actor_claims order by lower; 
 lower  | upper  | count 
--------+--------+-------
 140000 | 149999 |  4835
 150000 | 159999 |  2849
 160000 | 169674 |  3018
 170000 | 179999 |  2558
 180000 | 189996 |  4886
 190000 | 199997 |  4989
 200000 | 209996 |  5422
 210000 | 210998 |   516
(8 rows)

sentinel-analysis=> select * from visorstats.chain_powers order by lower; 
 lower | upper | count 
-------+-------+-------
     0 |     0 | 29392
(1 row)
```
