### ISSUE TITLE
schema: Flatten migrations

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#225]
As a semi-regular maintenance task, we should occasionally flatten the migrations which are no longer needing support.

### Acceptance Criteria
- [ ] Create Base Schema which represents the execution of migrations 0->X (TODO: What is X? Recommend latest migration ver in v0.3.0.)
- [ ] Make migrations 0->(X-1) error upon execution migrations and migration X should execute Base Schema creation.
- [ ] Update migrations README with note on flattening pattern employed here and what this means for a user trying to migrate existing data through a release pre-v0.3.0 and beyond. (Mentioned in discussion.)

### To Discuss
- What version should we flatten migrations up to? X must necessarily be something within the prior release and earlier (aka can't be unrelease in master). This approach would require anyone who doesn't which to start fresh to upgrade to v0.3.0 before upgrading further.

**Comment by iand** [comment]
Maybe this can be subsumed by #360
