### ISSUE TITLE
Init actor discrepancies

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#226]
### Describe the bug:

Processed all init actors from 140000 to 210000. 13707 actor state changes were processed, just 18 id addresses were produced:

```
  13707 initactor-140000-211000-actor_states.dump
  13707 initactor-140000-211000-actors.dump
     18 initactor-140000-211000-id_addresses.dump
  13707 initactor-140000-211000-visor_processing_actors.dump
  41139 total
```

### Steps to Reproduce:

This was the command line I ran

```
./visor --db postgres://localhost:5432/chainwatch?sslmode=disable --allow-schema-migration --lens=lotusrepo --repo=/srv/lotus_datadir_211000/ --log-level=debug  --log-level-named="vm:error,badger:info" run --td 5s --to 211000 --from 140000 --asw 100 --asb 1000 --asl 0 --actorstate-include=bafkqactgnfwc6mjpnfxgs5a --actorstate-include=bafkqactgnfwc6mrpnfxgs5a
```

### Visor Version

visor-v0.2.0+72-ge1942a5-dirty (iand/beefy branch)

This commit: https://github.com/filecoin-project/sentinel-visor/pull/221/commits/64d05f2a20119b5e7e3781966cdc486cd552352f

**Comment by iand** [comment]
Don't know if this is relevant but all 18 addresses produced had the same stateroot `bafy2bzacech3yb7xlb7c57v2xh7rvmt4skeidk7z2g36llksaz4biflblbt24`

**Comment by frrist** [comment]
Part of fix here: https://github.com/filecoin-project/lotus/pull/4875/files#diff-b901084d5eeba1521a114143d0f6d00a9bd12d9a2d836dee87ca8d7b704b8dfcL572-L575

Once this merges I'll update Visor to call this new diffing logic.
