### ISSUE TITLE
Make it easier to run multiple visor instances for historic ingests

### ISSUE THREAD

**Issue by thattommyhall** [filecoin-project/sentinel-visor#232]
### Description

We currently have some big machines and some manual steps to setup a machine with a copy of a lotus repo for historic ingestion. 

This involves running visor for combinations of task type+actor type and range of epochs on the chain and is currently also managed manually.

Proposal is to tidy this up so we can stand up as many as we need to churn through historic ingests.

### Acceptance criteria

"one click" setup and start of a visor ingest, in a way that allows for more parallelism

eg: 

```
./visor --db postgres://localhost:5432/chainwatch?sslmode=disable --allow-schema-migration --lens=lotusrepo --repo=/srv/lotus_datadir_211000/ --log-level=debug  --log-level-named="vm:error,badger:info" run --td 5s --to 211000 --from 140000 --asw 100 --asb 1000 --asl 0 --actorstate-include=BLAH --actorstate-include=PLOP
```

### Where to begin

The current snapshot is a "crash consistent" snapshot as far as I can tell, requiring us run xfs_check and to mount the repo rw.

- [x] see if can close the repo properly and mount it RO from multiple visor instances on same machine
- [x] see if can use an EFS mount instead of EBS (and what the performance hit is)
- [ ] Run a visor in AWS Batch / Step Functions

I think if we schedule the ingest in another tool, we might be able to avoid taking leases etc and sidestep having to do a bunch of performance fixes like #188 #183 etc

It might be better for me to start prepping an ingest in step functions on the assumption #222 lands quickly

**Comment by thattommyhall** [comment]
Talking to riba suggests no to being about to mount the database RO

**Comment by iand** [comment]
Closing since we've basically enabled this by adding csv output and offline processing.
