### ISSUE TITLE
Continuous Aggregates view for fee debt graphs

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/sentinel-visor#236]
### Description

Tracking the total fee debt in the network is an expensive operation.

A continuous aggregate query with a regular self-refresh (daily?) would help to keep a good view of the values and we could have it with high resolution (per epoch).

### Acceptance criteria

The view is created and materialized. 

### Where to begin

See completion of #235 for existing graphs.

There is an initial problem: to make an ongoing calculation which is not based on just the period we're looking into, we need to keep the separate fee-debt value for all miners that contribute to it. Otherwise, we are unable to know what we should carry-forward in to the next calculation (miners without fee-debt changes).

**Comment by frrist** [comment]
Please reopen if this issue is still relevant @hsanjuan
