### ISSUE TITLE
Add height to derived_gas_outputs

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/sentinel-visor#251]
### Description

Adding height should allow optimized JOIN with block_headers (current it either joins by state_root or by joining with intermediary tables like messages). It is slow.

### Acceptance criteria

Height column exists and populated (?).

### Where to begin

Gas Outputs model.

**Comment by hsanjuan** [comment]
Maybe this is a bad idea: to discuss

**Comment by hsanjuan** [comment]
Also, it might also be good to include the dst actor code directly.

**Comment by iand** [comment]
Fixed in https://github.com/filecoin-project/sentinel-visor/pull/270
