### ISSUE TITLE
Extract burnt funds account state

### ISSUE THREAD

**Issue by alanshaw** [filecoin-project/sentinel-visor#269]
The burnt funds account is a special account where all burnt funds resulting from gas costs are sent.

https://github.com/filecoin-project/specs-actors/blob/585b71e2b89642f2b01157c94e72a4ca9a8e869a/actors/builtin/singletons.go#L17-L18

Funds do not arrive via messages but are instead transferred by the VM implicitly. Tracking the f099 actor state allows us to analyse burn rates since we cannot inspect sent messages to see value transfer.

**Comment by frrist** [comment]
Can we query the actors balance from the actor_states table? I believe it's balance is stored in the state column.

**Comment by alanshaw** [comment]
I don't think we extract state from _any_ account actors.

**Comment by frrist** [comment]
closed via #278
