### ISSUE TITLE
State diff results in parent actor not found

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#273]
### Describe the bug:

When processing actor states we get a list of actor state changes using `state.Diff(parentStateTree, stateTree)`. We iterate the list of changes and process each one to extract and persist the state. The following actor consistently fails:

```
Height: 200021 
State root: bafy2bzaced6y7fdn4sdsrv6tsn3klwg33jybrihgvw7g26iwwp5bnedmj46dy
"Code": "bafkqaetgnfwc6mrpon2g64tbm5sw22lomvza", 
"Head": "bafy2bzacecahsf5ews4k4rjebw5inskbzjcvjw4v4pe2yozskok5jpvfgo6uq", 
"Name": "fil/2/storageminer", 
"Error": "failed to extract parsed actor state: creating miner state extraction context: loading previous miner f062897 at tipset {bafy2bzaceaqqqoxx34olk7tuyev6jz32m2eozjed2lk7brajgxknmppcsbmvq} epoch 200021: actor not found", 
"Address": "f062897"
```

### Visor Version

Found using this work in progress commit https://github.com/filecoin-project/sentinel-visor/commit/95d218b85c1e5e8d5c5987e290b26d65a7c9cf4c

**Comment by iand** [comment]
This is possibly a freshly created miner that doesn't have a previous state.

Another instance

```
{"height": 287133, "actor": "fil/2/storageminer", "address": "f094124", "error": "failed to extract parsed actor state: creating miner state extraction context: loading previous miner f094124 at tipset {bafy2bzacedodnmolpmswax5ooig4mbtv3sipgyeuferowf6gu2m2na5ceeosm,bafy2bzacedj5zswymdjwvnfc2an7pfaf5gim733krr57zevdwy5omkhvrox4o,bafy2bzacedpddii5bvf3d62omgpoeyxjyicz5zaspywi5d5m2zhhcvbnxnrss,bafy2bzacebq4zuxxkwsuf4ew43feulhidivxiqx2wkvx7eonfh2feepog5osq,bafy2bzaceadufcsoolc2ibqdrqy66c4yrw3t2x2zcyx5fybvevjvegacezbq4,bafy2bzacean2xj5nhtrt5cljqqwwpc5oxkmujixklwluxwpzrhw5hz7stghpg,bafy2bzacedcs3odk5bu4tjr5nwi3ns6y2sbjzws6w7s3nqyxyqovyua4hydom} epoch 287133: actor not found"}
```

**Comment by frrist** [comment]
To debug I picked account actor `f0466359` from the `visor_processing_report` table as it has a similar error: 
```
[{"Code": "bafkqadlgnfwc6mzpmfrwg33vnz2a", "Head": "bafy2bzacebgdwerb5ucln5nep7iwvbhlyy5fpxrzlq3pqurkhrmhl7qns3fci", "Name": "fil/3/account", "Error": "failed to extract parsed actor state: getting actor: actor not found", "Address": "f0466359"}]
```
(the command `./visor --lens="lotusrepo" --repo="~/.lotus" walk --from=624269 --to=624269 --tasks=actorstatesraw` can be used to reproduce this)

Based on debugging so far, these errors are being returned from here:
https://github.com/filecoin-project/lotus/blob/1f62c07789535980e848fd805c8165dafd04a5c7/chain/state/statetree.go#L337

Will continue to update as I debug.

**Comment by frrist** [comment]
This seems to be the culprit: https://github.com/filecoin-project/sentinel-visor/blob/de2eda07705a7efaccd454063a9082d7c855f805/tasks/actorstate/task.go#L152

when we call Extract using `ActorInfo` the `ActorExtractor` calls `StateReadState` on the lotus API: 
https://github.com/filecoin-project/sentinel-visor/blob/de2eda07705a7efaccd454063a9082d7c855f805/tasks/actorstate/actor.go#L26
calls `LoadActor`
https://github.com/filecoin-project/lotus/blob/f4a2c8fa49dfc456090f5a5ea1b4ae62d33b4f85/chain/stmgr/read.go#L44
calls `ParentState`:
https://github.com/filecoin-project/lotus/blob/f4a2c8fa49dfc456090f5a5ea1b4ae62d33b4f85/chain/stmgr/read.go#L45
using the tipset we passed in -- the ParentTipSet @ height 624268 its parent state is 624267, meaning we are looking back too far.
