### ISSUE TITLE
Missing data in miner_sector_deals

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/sentinel-visor#280]
### Describe the bug:

It seems this table has a miner-id/sector-id primary key: https://github.com/filecoin-project/sentinel-visor/blob/master/storage/migrations/2_visor_initial.go#L85

This means that there will be only one row per combination of those. However, a miner-sector may have multiple deals in them, so we are missing rows for all deals in sectors except the first.

### Steps to Reproduce:

Many activated deals have no entries in miner_sector_deals.

### Visor Version: master.

@iand

**Comment by frrist** [comment]
Will also need a change to the ORM model here: https://github.com/filecoin-project/sentinel-visor/blob/master/model/actors/miner/sectordeals.go#L18
