### ISSUE TITLE
Implement mocks for Lease<thing> and Mark<thing>Complete storage methods

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel-visor#288]
### Description
Many processors call a `Lease<thing>()` and `Mark<thing>Complete()` method while processing data. To ease test-ability of these processors mocks should be create for these methods.

### Acceptance criteria
- [ ] Mock `LeaseStateChanges` and `MarkStateChangeComplete`
- [ ] Mock `LeaseActors` and `MarkActorComplete`
- [ ] Mock `LeaseTipSetMessages` and `MarkTipSetMessagesComplete`
- [ ] Mock `LeaseGasOutputsMessages` and `MarkGasOutputsMessagesComplete` 
- [ ] Mock `LeaseTipSetEconomics` and `MarkTipSetEconomicsComplete`

**Comment by iand** [comment]
I would hold off implementing this since we are moving away from leasing

**Comment by frrist** [comment]
Good idea. May revisit later.
