### ISSUE TITLE
Lotus API is very chatty

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#302]
One reason why full extraction of actor data is slow is that the Lotus API is very chatty. Indexing one tipset fully involved around 2 million API calls. Caching can reduce the load on Lotus but the round trip time makes the process very slow.

This issue is to capture ideas for improving this such as by adding new batch-oriented API methods to reduce the number of round trips.

**Comment by thattommyhall** [comment]
Wondering if the cache can be smarter and pre-fetch a bunch of stuff based on what is being asked for. But improvements to lotus itself is probably more broadly useful

**Comment by iand** [comment]
Working on a doc to kick of discussion

**Comment by frrist** [comment]
I think we can consider this closed now that we are moving to lily
