### ISSUE TITLE
Default application names cause startup error "unknown startup message response: 'N'"

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#307]
With the following default application name (`visor_v0.4.0+rc1-dirty_sentinel-monitoring-stag-visor-d476cc8bf-csmxx_3851`), visor startup was fatally erroring:

`2020-12-08T16:10:04.458Z        FATAL   visor   sentinel-visor/main.go:137      setup database: connect database: connect: ping database: pg: unknown startup message response: 'N'`

## Acceptance Criteria
- validate the length of the `--name` is less than 64 characters

**Comment by frrist** [comment]
Any chance the name is too long? From the docs:
> The application_name can be any string of less than NAMEDATALEN characters (64 characters in a standard build).

```shell
$ echo visor_v0.4.0+rc1-dirty_sentinel-monitoring-stag-visor-d476cc8bf-csmxx_3851 | wc -c
75
```

**Comment by placer14** [comment]
Seems that could definitely be the case. Still don't know what the N was truncated from, but it's likely a NOTICE which says as much. Whether there is fix to apply upstream or not, the error response could at least be adjusted to show more of the remote error.

**Comment by iand** [comment]
I don't think we need to fix this since our deployments can just specify a name using `--name` and it seems sensible to use that to give a meaningful name to the instance such as `monitoring`. K8s is notorious for generating long names.

**Comment by iand** [comment]
> Seems that could definitely be the case. Still don't know what the N was truncated from, but it's likely a NOTICE which says as much. Whether there is fix to apply upstream or not, the error response could at least be adjusted to show more of the remote error.

The 'N' is just a code in the pg protocol, I don't think it is truncated from anything.
