### ISSUE TITLE
Move refreshing of materialized views out of Visor

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#310]
### Description

Create a new way of refreshing materialized views on a schedule. This could be a new application or a cron job in k8s. Keep Visor responsible for extracting and writing data to the database. There may be other views, not used by visor, that could benefit from automatic refreshing.

### Acceptance criteria

 - Materialized views can be refreshed without using Visor
 - Remove refreshing task from Visor

### Where to begin

 - Look into creating a k8s CronJob that can be deployed via Helm.

**Comment by iand** [comment]
This is probably superceded or part of https://github.com/filecoin-project/sentinel/issues/176

**Comment by frrist** [comment]
Going to close this as https://github.com/filecoin-project/sentinel/issues/176 aims to address it.
