### ISSUE TITLE
Capture comprehensive reorg state as part of Monitoring

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#317]
In order to capture reorg and orphaned blocks across network, reconsider capture of data via drone and/or visor required.

Acceptance Criteria
- review requirements to support answering blocked issues

**Comment by iand** [comment]
Can you expand on the requirements here. What data is missing? Currently this reads as an issue to create another issue.

**Comment by frrist** [comment]
We can reopen this when more details around requirements are available.
