### ISSUE TITLE
Investigate visor behaviour and data written during chain halt

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#336]
### Description

Around 2020-12-19 17:49 UTC the filecoin chain halted at height 336459. An updated version of Lotus was deployed and the chain resumed syncing after several hours of competition between multiple short lived forks. By 2020-12-20 01:13 UTC (around height 337120) the chain was fully in sync. We should investigate how Visor behaved during this period and which blocks were indexed to determine if any behaviour changes are needed.

**Comment by PatrickDeuse** [comment]
i have a fully synced chain from a snapshot that was created after the "crash" indexed with visor - if you need any info let me know.

**Comment by iand** [comment]
CLosing due to age
