### ISSUE TITLE
Init actor diff expects writable store

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#362]
### Describe the bug:

`failed to extract parsed actor state: diffing init actor state: writing map root object: put is not implemented on CacheCtxStore`

### Steps to Reproduce:

Run `visor walk --tasks=actorstatesinit` against heights with an init actor change such as 413117 or 413798

**Comment by frrist** [comment]
closed via https://github.com/filecoin-project/sentinel-visor/pull/519
