### ISSUE TITLE
Update with final Lotus v1.5.0 release/complete v3 specs-actors upgrade

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#373]
This is a chore to complete the v1.5.0 release upgrade once the final version is tagged.

## Acceptance Criteria

- [ ] Include final v1.5.0 lotus release (blocked)
- [ ] Include updated state-diff changes (blocked)

**Comment by iand** [comment]
Lotus have tagged 1.5.0

Also need to include https://github.com/filecoin-project/statediff/releases/tag/v0.0.18
