### ISSUE TITLE
Reconcile semantics between Lotus API and Visor `actor_state` schema

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#381]
Are the heights recorded within `actor_states` off by -1? The following inconsistency was found when interacting with a lotus node versus what was captured in the schema ingested from visor.

<details>
<summary>Log detail</summary>

```javascript
const tipsetNext = await this.lotus.client.chain.getTipSetByHeight(485819);
console.log(tipsetNext.Cids);
const state = await this.lotus.client.state.readState('f06',tipsetNext.Cids);// infuraWrapper.stateReadState('f06', tipsetNext.Cids);
console.log('state',state);
output for height 485817:
 [
   {
     '/': 'bafy2bzacealok4sluvaiabyinf7tefqijqeggtpvfcmahrqmthcabg2bwbfli'
   },
   {
     '/': 'bafy2bzaceafhceghbovgs77no2obzjfelpb4fjyimkausfs7qxu3hd22dhyjs'
   },
   {
     '/': 'bafy2bzacecy67lvkroit5e7qao6ae4ezlybhwlo5wdletxrdzqdjxozxe4boq'
   },
   {
     '/': 'bafy2bzacecxadtvdxpnkmyvor2on2dt6z6sxcaiix5kaqombnxwmnw5nggwvc'
   }
 ]
 state {
   Balance: '0',
   State: {
     RootKey: 'f080',
     Verifiers: {
       '/': 'bafy2bzacedthxuodxlcnzqlbgtvgls6pbvsbv2jfuskn5xpzldssvv7jsxxa2'
     },
     VerifiedClients: {
       '/': 'bafy2bzacea5woqjyqtzmnuydiblcfxscrtouj2kqo2plagdn76edq7o45qyiy'
     }
   }
 }
output for height 485818, 485819:
 [
   {
     '/': 'bafy2bzacebrcncmrvmq3t4h7niq6tdzrhc5sd6fi3ktdi6bm7jhxb2442zudm'
   }
 ]
 state {
   Balance: '0',
   State: {
     RootKey: 'f080',
     Verifiers: {
       '/': 'bafy2bzacedthxuodxlcnzqlbgtvgls6pbvsbv2jfuskn5xpzldssvv7jsxxa2'
     },
     VerifiedClients: {
       '/': 'bafy2bzacedi4zn4fyng735tc7pg474hvcewje47jr6ftcpew35pcfddzmwcu2'
     }
   }
 }
 
State from db at height 485819 :
{
"RootKey": "f080", 
"Verifiers": {"/": "bafy2bzacedthxuodxlcnzqlbgtvgls6pbvsbv2jfuskn5xpzldssvv7jsxxa2"}, 
"VerifiedClients": {"/": "bafy2bzacedi4zn4fyng735tc7pg474hvcewje47jr6ftcpew35pcfddzmwcu2"}
}
```

</details>

In order to have consistent semantics across the ecosystem, it's preferred that our captured data follow its source of truth. The above javascript interactions are directly tied to the API of lotus.

## Acceptance Criteria
- determine whether the semantics of the data captured by visor match the semantics exposed by the lotus API
  - if the semantics differ from lotus and its clear that visor should shift, deliver a migration which aligns the schema with the API
  - if the semantics differ and clarity is required on how to shift, a discussion should be explored toward reconciling the lotus API and schema as appropriate. This discussion should resolve to clear actionables for either the API or visor
  
## Where to begin
- Compare the lotus API semantics (around `state.readState` and `chain.getTipSetByHeight(height).Cids` as used in the above example) to Visor capture semantics (how these functions are used to persist data into `actor_states` to identify where they differ (if at all).
- Attempt to develop recommended next steps on this and get consensus on approach with the core contributors of `sentinel-visor`.

**Comment by hsanjuan** [comment]
@frrist with all the off-by-one bug, is there a chance that this was fixed?

**Comment by frrist** [comment]
I believe https://github.com/filecoin-project/sentinel-visor/commit/0f71b33aff4cbc4db4deeec1f84acd0c5e3eaa34 in conjunction with the Lotus API changes around parent state has addressed this.
