### ISSUE TITLE
parsed_messages: method "unknown.X"

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/sentinel-visor#387]
### Describe the bug:

The `parsed_messages` table contains messages with methods marked as "unknown".

### Steps to Reproduce:

```sql
select
  "method"
from
  parsed_messages
where
  height > 500000 --otherwise takes long
  and method like 'unknown%'
group by
  method
```

**Comment by frrist** [comment]
It looks like this could be caused by a message with a method not contained in the statediff method table:
https://github.com/filecoin-project/sentinel-visor/blob/6bd14288df3c86877eb5b620a979ca6d2c5081ab/chain/message.go#L269-L273

**Comment by willscott** [comment]
It can also happen in cases where we haven't determined the type of actor that the message is being sent to (which can happen if the actor is new in that block or implicit or potentially some other edge cases)

**Comment by willscott** [comment]
do we see that a lot? are there specific numbers for the unknown method number that seem to be most of them?

**Comment by frrist** [comment]
From a glance at the calibration and mainnet database's this has been addressed.
