### ISSUE TITLE
Track multisig transactions

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/sentinel-visor#388]
### Description

We have no sentinel-record when a multisig transaction happen.

### Acceptance criteria

Ideally there will be a table with all multisig-related transactions, that includes the height, the proposer, the approvers, the amount and the destination.

Simplified acceptance criteria, since I don't see an easy, quick way to do the above:

- height, multisig_id, proposal, amount, propose_message_cid, multisig_threshold, decoded_proposal_params

only when the multisig threshold is 1 (auto-approval).

(figure out the rest later, which will complete the table with transactions for which the approval happend with higher thresholds).

### Where to begin

See derived_gas_outputs. The propose messages that end up adding content to this table should only be those with successful exit code.

**Comment by alanshaw** [comment]
Just to ensure all the info is captured: `mutlisig_transactions` is almost able to tell us when a transaction is approved and executed as it tracks state for multisig actors.

The table tracks the `PendingTxns` state on the multisig actor. When a transaction meets approval threshold the (implicit) send is performed and the transaction is REMOVED from the list.

I believe the diff _will detect the removal_ but nothing is done with the information.

If we could add a row to the table when a transaction is removed from `PendingTxns` then we can track the transaction execution.

Caveats apply - transactions _can_ be canceled but we can detect this by inspecting the balance (it won't change for a cancel).

As a side note, for completeness we really should add something to the table for _all_ state changes regardless of what we need it for.

**Comment by iand** [comment]
> I believe the diff _will detect the removal_ but nothing is done with the information.

I think we could enumerate the removals in this section of code https://github.com/filecoin-project/sentinel-visor/blob/master/tasks/actorstate/multisig.go#L78

We could add the removals to the `multisig_transactions` table but we'd need to flag them in some way to distinguish them from additions/modifications

**Comment by hsanjuan** [comment]
I don't think anything lands on PendingTxns for multisig transactions need no additional approvals other than that of the proposer. Those are shortcut and executed directly on proposal. And those are the ones that interest me most.

**Comment by alanshaw** [comment]
> I don't think anything lands on PendingTxns for multisig transactions need no additional approvals other than that of the proposer. Those are shortcut and executed directly on proposal. And those are the ones that interest me most.

Ahhh, yes looking at the code I think you're right. 🤦‍♂️
