### ISSUE TITLE
"failed to extract parsed actor state: no state change detected"

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/sentinel-visor#397]
`2021-02-21T15:05:58.642+0100	ERROR	chain	chain/actor.go:92	actor returned with error	{"height": 3159, "actor": "fil/3/storagemarket", "address": "t05", "error": "failed to extract parsed actor state: no state change detected"}`

is this really an error? 

were just indexing the new calibnet and as expected this comes up with every block

**Comment by iand** [comment]
I think this is simply the market actor extractor not finding any *relevant* changes. Doesn't need to be an error, just return with no data extracted.

**Comment by hsanjuan** [comment]
This seems fixed in master. Blame points to 0f71b33aff4cbc4db4deeec1f84acd0c5e3eaa34 .
