### ISSUE TITLE
Possible missing messages from blocks

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel-visor#426]
### Describe the bug:
[Initial Slack Thread for context
](https://protocollabs.slack.com/archives/CT2265RFZ/p1616087045025000)

Message CID `bafy2bzaceac36ranzqs5jg66b4qlchhcufpxkiai6e7lc3l25cq2sftcl7ziu` appears in blocks:
`bafy2bzacecmca4wktk4vclyfyifem57v55hotbuaw4i3ojrpcrny675jggrkq` (Latest 238 Messages)
`bafy2bzacebmfagqhkl73syvvxlynk3tdbmdhh3yn2gwggulttjczasov345ne` (Latest 238 Messages)
`bafy2bzacebpix3zkybskexmpjyb5wfcx7q4pdnb5ijv7zwt4w3ybhxmewfbyi` (Latest 240 Messages)

Source FilFox: https://filscan.io/tipset/message-detail?cid=bafy2bzaceac36ranzqs5jg66b4qlchhcufpxkiai6e7lc3l25cq2sftcl7ziu

This messages is not found in Sentinel Production Monitoring and the aforementioned blocks have a different number of messages than FilFox:

`select count(message) from block_messages where block = 'bafy2bzacebpix3zkybskexmpjyb5wfcx7q4pdnb5ijv7zwt4w3ybhxmewfbyi' and height = '590662'`
Count: 239

`select count(message) from block_messages where block = 'bafy2bzacebmfagqhkl73syvvxlynk3tdbmdhh3yn2gwggulttjczasov345ne' and height = '590662'`
Count: 236

`select count(message) from block_messages where block = 'bafy2bzacecmca4wktk4vclyfyifem57v55hotbuaw4i3ojrpcrny675jggrkq' and height = '590662'`
Count: 236

### Visor Version: Sentinel Production Monitoring

**Comment by frrist** [comment]
Working through this issue now, half the battle is getting the right state locally to reproduce this, here are the steps I followed:

#### Sync lotus from an old snapshot:
```
$ lotus daemon --snapshot=https://fil-chain-snapshots-fallback.s3-us-west-2.amazonaws.com/mainnet/minimal_finality_stateroots_590860_2021-03-18_02-00-00.car
```
(wait for this to complete downloading, you don't need to wait for it to fully catch up)

#### Reset your louts head
```
$ lotus chain sethead --epoch=590000
```

#### Kill your node and restart it:
```
killall lotus
```
```
lotus daemon
```

#### Observe your sync worker is at height 590000
```
lotus sync status 
```

Now after the lotus node syncs past `590662` your repo will contain all state needed to debug.

**Comment by frrist** [comment]
Message `bafy2bzaceac36ranzqs5jg66b4qlchhcufpxkiai6e7lc3l25cq2sftcl7ziu` is missing from the aforementioned blocks (`bafy2bzacecmca4wktk4vclyfyifem57v55hotbuaw4i3ojrpcrny675jggrkq`,`bafy2bzacebmfagqhkl73syvvxlynk3tdbmdhh3yn2gwggulttjczasov345ne`,`bafy2bzacebpix3zkybskexmpjyb5wfcx7q4pdnb5ijv7zwt4w3ybhxmewfbyi`) because its sender `    f1o47rfkl2fohkv4si6rlawuzkpnlppetum32bbga` sent a message `bafy2bzacedmhulwuxiwdjgt5e34cfoq5o3w4zlrojcwxtyy4tzf4a2t4i6dh6` with the same nonce (146) that was executed successfully: https://filfox.info/en/message/bafy2bzacedmhulwuxiwdjgt5e34cfoq5o3w4zlrojcwxtyy4tzf4a2t4i6dh6

**Comment by iand** [comment]
Does the duplicate message have receipt?

**Comment by iand** [comment]
We should aim to include all messages in `messagemodel.BlockMessages` - it's a bug if there are messages in blocks that are not saved to that table.

**Comment by frrist** [comment]
> Does the duplicate message have a receipt?

It does not -- since the message was never executed. In this specific case, the message was ignored because an earlier block in the tipset contained a msg with the same sender+nonce (that message can be seen here: https://filfox.info/en/message/bafy2bzacedmhulwuxiwdjgt5e34cfoq5o3w4zlrojcwxtyy4tzf4a2t4i6dh6) (here is where the filtering on messages like these is performed in lotus: https://github.com/filecoin-project/lotus/blob/7bced1532b93ee7bd3757aca247249f67b953e33/chain/store/store.go#L1011)

> We should aim to include all messages in `messagemodel.BlockMessages` - it's a bug if there are messages in blocks that are not saved to that table.

Agreed. The next question is: Should we also aim to include all messages in `messagemodel.Messages`? 
Currently, the table only contains executed messages -- meaning we have no way to inspect a message found in `messagemodel.BlockMessages`.

**Comment by iand** [comment]
Lets defer capturing the messages into the messages table, focus on getting them into block_messages
