### ISSUE TITLE
Move parameters from main to subcommands

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#453]
### Description

Many parameters are currently specified on the `visor` command but are only relevant for non-daemon watches or walks. We should make them common parameters to the `visor run walk` and `visor run watch` commands. 

Instead of:

```
visor --api=blah --db=bleugh --lens=lotus run watch
```

we should have

```
visor run watch --api=blah --db=bleugh --lens=lotus
```

### Acceptance criteria

The following parameters should be usable from `visor run watch` and `visor run walk`

 - lens
 - repo
 - repo-read-only
 - api
 - db
 - db-pool-size
 - db-allow-upsert
 - allow-schema-migration
 - lens-cache-hint
 - name
 - lens-postgres-namespace
 - lens-postgres-preload-recents
 - lens-postgres-get-prefetch-depth

The following parameter should be usable from `visor migrate`

 - db

**Comment by frrist** [comment]
closed via https://github.com/filecoin-project/sentinel-visor/pull/464
