### ISSUE TITLE
actorstatesmultisig reporting null value in params column

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#459]
### Describe the bug:

{"level":"error","ts":"2021-04-09T14:51:36.645Z","logger":"chain","caller":"chain/indexer.go:356","msg":"persistence failed","height":655753,"task":"actorstatesmultisig","error":"persisting model: ERROR #23502 null value in column \"params\" violates not-null constraint","errorVerbose":"persisting model:\n    github.com/filecoin-project/sentinel-visor/storage.(*TxStorage).PersistModel\n        /go/src/github.com/filecoin-project/sentinel-visor/storage/sql.go:322\n  - ERROR #23502 null value in column \"params\" violates not-null constraint"}

**Comment by frrist** [comment]
This looks like a bug in our model migration code:

https://github.com/filecoin-project/sentinel-visor/blob/1566ccb2fd68b3e4cc3e2676d9c1f38dc417314d/model/actors/multisig/transactions.go#L20

https://github.com/filecoin-project/sentinel-visor/blob/1566ccb2fd68b3e4cc3e2676d9c1f38dc417314d/storage/migrations/18_msig_transactions.go#L20

The model should allow null Multisig transaction params (e.g. when performing a simple send they are null)
