### ISSUE TITLE
Does sentinel support capturing orphan blocks?

### ISSUE THREAD

**Issue by Icarus9913** [filecoin-project/sentinel-visor#461]
### Description
I have checked the sentinel source codes, but not sure whether sentinel supports capturing orphan blocks. If could, plz tell me where the codes locate ok? Thanks.

**Comment by hsanjuan** [comment]
It generally does not capture orphan blocks, though it may if the confidence level is very low. When it does, they are included with the rest of blocks in the block_headers table etc. Normally we run with high confidence level to avoid spurious data from orphan blocks.

We might look for ways to identify and track them in the future. Closing this in favour of https://github.com/filecoin-project/sentinel-visor/issues/317
