### ISSUE TITLE
Add `height` to tables without height

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/sentinel-visor#484]
Tracking all tables that need height:

* `id_addresses`
* `chain_economics`

**Comment by thattommyhall** [comment]
For the Parquet exports, it's nice to have something that can be related to a datetime, as well as `id_addresses` `height` is missing from `chain_economics` and there we have `parent_state_root`

**Comment by hsanjuan** [comment]
We should have height in all tables

**Comment by thattommyhall** [comment]
I did go through all the existing schemas so I am pretty sure those 2 are all (tho the drand one is round, not height)
