### ISSUE TITLE
visor daemon has no stop command

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/sentinel-visor#550]
### Describe the bug:

visor daemon cannot be gracefully shut down - it does not make the lotus stop command available

**Comment by frrist** [comment]
`Ctrl+C` - SIGINT will stop the visor daemon. Please reopen with motivation for adding a `visor daemon stop` command, assuming that's what you mean.

**Comment by frrist** [comment]
Releated PR: https://github.com/filecoin-project/sentinel-visor/pull/568/files
