### ISSUE TITLE
Decode bitfields

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/sentinel-visor#569]
### Description

Some message params and states have bitfield types. This particularly affects ProveCommitAggregate message params.

In our JSONb serializations, we are just storing the bitfields bytes (which are an RLE+ serialization of a bitfield I think) and it is difficult to work with this.

Bitfields are serialized in JSON as array of run-lengths which is also hard to work with. Ideally, what we'd want is an array with the list of elements in the set (https://github.com/filecoin-project/go-bitfield/blob/master/rle/rleplus.go#L71).

Without having this list we cannot, for example, know how many sectors are being proved on a batch commit.

**Comment by hsanjuan** [comment]
It has been pointed out that small bitfields can potentially expand to really large sets.

Thus my current proposal is to decode them as `{ "type": "bitfield", "RLE": <MarshalJSON>, "ElemCount": Count()}`.

At some point we can add a function that expands the RLE to set.

**Comment by hsanjuan** [comment]
Alternatively, we could set a Max and avoid decoding very unreasonably large sets.

**Comment by frrist** [comment]
Made the changes request above and ran this against calibration, here is what the below query returns now:
The first column, RLE is the son marshaled RLE encoded bit field, the second column ElemCount is the `Count()` of the RLE bitfield.
```sql
select params#>'{SectorNumbers,RLE}' as RLE,
       params#>'{SectorNumbers,ElemCount}' as ElemCount
from parsed_messages
where method = 'ProveCommitAggregate'
```

|rle|elemcount|
|-|-|
|[900,1,556,1,12,1,1,1,141,1,13,1,13,1,11,1,3,1,40,2,23,1,3,1,2,1,3,1,10,1,16,1,3,1,1,1,4,1,33,1,3,1,1,1,1,1,3,1,7,1,2,1,2,1,2,1,5,1,2,2,5,2,8,2,3,1,1,1,15,1,83,1,6,2,6,1,1,1,2,1,5,2,1,1,3,1,5,1,3,2,1,1,4,1,5,1,1,1,1,1,1,4,6,1,1,1,2,1,1,3,3,1,1,4,1,6,2,3,2,3,1,1,1,4,2,1,1,1,7,1,6,1,4,1,1,1,4,1,2,1,1,2,1,2,1,1,1,1,7,1,7,1,21,1]|106|
|[91,4,1,4]|8|
|[50,1,8,1,22,1,4,1]|4|
|[50,2,1,1,1,3,1,1,1,1,1,2,1,1,5,1]|12|
|[48,2,5,1,10,1]|4|
|[69,1,2,1,3,1,1,1,4,1,3,1,1,2]|8|
|[15,1,27,1,5,1,12,1]|4|
|[71,1,1,2,4,3,2,1,1,1]|8|
|[128,1,112,1,11,1,26,1,195,1,1,1,2,1,19,1,99,1,12,1,3,1,4,1,18,1,1,1,2,1,4,1,90,1,7,1,5,2,1,1,8,2,1,1,3,1,1,2,1,1,2,1,3,1,25,1,6,1,2,2,4,2,2,2,1,1,9,1,19,1,8,1,15,1,3,1,2,1,1,1,2,1,9,1,16,1,1,1,4,1,14,2,4,1,1,1,8,1,2,1,4,1,8,1,2,5,1,1,2,4,1,3,1,1,5,4,1,4,1,3,1,3,3,1,1,2,1,1,4,3,2,2,1,1,1,1,1,2,1,20,4,1,1,1,2,1,1,1,2,1,2,4,1,1,6,1,7,1,5,1,2,2,7,2,2,3,1,1,1,1,1,1,5,2,3,2,2,1,1,1,1,1,1,2,1,2,2,4,2,4,3,2,1,2,1,2,1,1,3,1,1,2,1,5,1,1,1,3,1,8,1,3,1,4,1,102,1,34,1,14,1,22,1,46,1,4,1,3,1,1,6,1,1,6,1,2,1,47,1,23,1,3,1,18,1,7,1,7,1,15,1,1,1,5,1,7,1,4,1,8,1,4,1,5,4,1,2,13,1,25,2,6,2,5,3,1,1,5,1,1,1,1,1,2,1,3,1,10,2,1,1,3,1,3,3,3,5,1,4,1,2,1,1,4,1,2,1,1,1,2,1,5,1,2,1,4,1,1,1,1,1,2,2,1,1,1,1,3,1,7,2,1,4,2,8,1,2,4,4,3,1,1,1,1,2,2,2,1,4,1,1,1,1,1,3,1,5,1,1,1,1,4,1,1,1,14,1,1,1,1,1,1,2,2,1,2,1,2,1,1,2,1,2,1,1,3,1,3,1,24,1,3,1,2,2,4,3,1,4,1,8,1,1,1,2,4,1,3,10,4,1,1,1,1,7,1,3,1,14,1]|819|
|[67,2,1,1,4,1,1,1,4,1,2,1,2,1]|8|
|[0,5]|5|
|[3,4]|4|
|[47,1,6,1,1,1,7,1]|4|
|[1,1,3,1,22,1,1,1]|4|
|[39,2,4,1,5,1]|4|
|[4,1,3,1,9,2,13,1]|5|
|[2,2,16,1,2,2]|5|
|[11,3,11,1]|4|
|[10,1,3,1,1,2,3,1,5,1,1,1]|7|
|[6,2,1,1,12,1,3,1]|5|
|[16,1,73,1,14,1,59,1]|4|
|[10,2,1,2,3,1,6,2,3,1,4,2,3,2,4,1,2,2,1,1,1,2,2,1,1,1,4,2,2,1,2,2,2,2,5,1,1,1,1,2,2,4,1,3,2,1,6,2,1,1,5,1,1,2,3,3,2,1,1,3,2,2,1,1,1,2,5,3,4,1,1,1,2,3,5,2,3,3,6,1,2,1,3,1,2,1,1,2,3,1,1,3,1,1,1,3,2,1,3,1,3,2,2,1,2,1,6,2]|92|
|[3,3,6,1,15,2,13,2,37,1,1,1,19,1,8,1,8,1,11,2,2,1,4,2,1,1,24,1,11,1,12,3,1,1,16,1,4,1,2,1,13,2,2,2]|32|
|[47,1,158,1,22,1,6,1]|4|
|[41,1,1,1,2,1,2,1,1,2,2,1,4,1]|8|
|[28,1,2,1,3,1,3,1]|4|
|[0,1,29,3]|4|
|[56,4,1,4]|8|
|[35,1,1,1,4,1,1,1]|4|
|[42,1,1,2,1,2,1,1,2,2]|8|
|[0,6]|6|
|[56,1,36,1,4,1,3,1,43,1,8,1,13,1,40,1,11,2,2,3,4,5,1,2,1,4,3,3,2,2,1,2,1,4,1,1,1,2,1,4,1,5,1,1,175,1,2,1,3,1,2,1,2,1,2,3,1,1,1,2,2,1,1,2,2,4,7,1,3,1,2,1,4,1,2,1,1,1,3,1,3,1,3,1,2,1,16,1,11,1,5,1,3,1,1,1,3,1,2,1,1,19,1,12,1,3,1,4,2,2,1,14,1,1,1,2,1,4,1,3,3,1,5,1,6,1,2,2,1,2,1,4,1,1,1,9,1,5,1,2,1,2,1,14,1,18,2,2,1,3,1,5,2,1,1,8,2,1,1,3,1,1,2,1,1,2,1,3,1,25,1,6,1,2,2,4,2,2,2,1,1,9,1,19,1,8,1,15,1,3,1,2,4,1,1,5,1,3,1,16,1,1,1,2,1,1,2,13,2,4,1,1,1,8,1,2,1,4,1,8,1,2,5,1,1,2,4,1,3,1,1,5,4,1,4,1,3,1,3,3,1,1,2,1,1,4,3,2,2,1,1,1,1,1,2,1,20,4,3,2,1,1,1,2,1,1,5,1,1,6,1,7,1,5,1,2,2,7,2,2,3,1,1,1,1,1,1,5,2,3,2,2,1,1,1,1,1,1,2,1,2,2,4,2,4,3,2,1,2,1,2,1,1,3,1,1,2,1,5,1,1,1,3,1,8,1,3,1,4,1]|512|
|[46,1,51,2,3,2,1,1,14,1,1,1,8,1,4,1,1,1,1,1,12,1,4,1,8,1,1,2,9,2,3,2,39,2,7,1,8,1,8,2,6,1,15,1,3,1,20,1,2,1,13,1,18,1,1,1,4,1,10,1,5,1,10,1,5,2,5,1,10,1,4,1,2,2,10,1,18,1,5,1,2,1,59,1,1,1,9,1,1,1,33,2,7,1,2,1,2,1,8,2,2,1,1,1,2,1,2,2,2,2,1,2,1,1,16,1,2,1,2,1,2,1,14,1,3,1,27,1,8,1,9,10,1,1,1,1,1,7,2,1,3,1,4,1,2,1,2,1,1,1,1,4,1,1,4,2,2,2,1,2,3,1,2,1,1,2,1,2,1,1,2,2,2,1,5,1,3,1,1,1,2,1,1,2,1,1,1,1,1,2,2,1,1,2,1,4,4,13,1,3,2,1,2,1,1,5,2,2,2,4,1,2,1,1,1,3,1,2,1,2,1,6,1,1,1,4,1,1,3,17,1,2,1,7,3,2,1,2,2,2,4,1,2,1,5,2,1,1,2,3,1,2,2,1,1,2,1,1,1,2,1,3,1,1,1,1,1,1,1,1,1,3,11,1,6,1,6,1,5,1,1,1]|256|
|[31,1,1,1,2,1,1,1,2,1]|5|
|[1,1,2,1,6,2]|4|
|[25,1,1,2,5,1]|4|
|[26,1,2,1,2,1,1,1,1,2,1,2]|8|
|[1,55,1,36,1,4,1,3,1,25,1,17,1,8,1,13,1,2,1,5,1,21,1,9,1,11,2,2,3,4,5,1,7,3,3,1,3,1,7,1,1,1,7,1,7,66,1,108,1,2,1,3,1,2,1,2,2,1,9,1,1,1,2,2,4,7,2,2,1,2,1,4,1,2,1,1,1,3,1,3,1,3,1,2,1,16,1,11,1,5,1,3,1,1,1,3,1,2,1,1,42,1,2,1,28,3,1,5,1,6,1,2,2,1,2,1,4,1,1,1,9,1,5,1,2,1,2,1,14,1,19,1,2,1]|512|
|[17,1,1,1,1,1,8,1,1,1]|5|
|[7,23]|23|
|[14,1,1,1,9,1,2,1]|4|
|[28,1,15,1,3,2,29,2,13,4,7,1,1,1,12,1,14,2,5,1,1,2,1,3,3,1,6,3,1,2,1,1,1,1,2,1,1,3,1,3,4,1,13,5,1,1,6,4,5,1,1,2,13,1,2,1,4,1,17,1,6,1,5,1,2,1,12,1,1,1,6,1,2,1,5,1,1,1,17,1,19,1,4,1,3,1,11,1,13,1,2,1,52,1,22,1,2,1,2,2,1,3,1,2,1,1,5,3,2,5,1,2,1,5,1,1,20,4,2,3,4,1,3,1,2,6,3,2,1,2,2,2,4,1,1,5,3,2,1,1,1,1,2,2,2,2,2,1,2,1,1,1,1,14,2,1,1,1,2,2,1,2,2,10,1,3,1,13,4,1,1,8,2,4,1,2,1,2,17,1,1,1,1,1,7,2,1,1,1,1,1,3,2,2,1,1,2,1,6,1,1,1,1,2,2,2,2,1,3,2,1,1,2,1,2,1,2,1,1,1,3,2,1,3,1,1,1,3,1,1,1,2,4,1,1,1,1,1,2,2,4,1,4,2,1,1,13,1,3,2,10,2,3,1,4,1,31,2]|256|
|[9,1,3,1,6,1,3,1]|4|
|[6,1,1,1,6,1,2,1]|4|
|[25,1,1,2,1,2,1,1,1,1,2,1]|8|
|[5,1,1,1,2,1,12,1]|4|
|[15,1,5,1,4,2,1,1,2,1,1,5,1,2,5,1,3,1,35,2,1,4,6,2,7,2,1,4,2,1,3,1,1,6,1,1,1,1,4,1,4,1,2,1,3,2,3,4,4,1,9,1,10,1,3,6,1,4,7,2,1,3,4,5,1,1,2,1,3,1,1,5,1,1,2,1,2,2,2,4,1,2,2,6,1,1,1,6,1,2,1,2,4,1,3,8,1,1,1,5,3,1,3,1,1,1,1,1,2,5,1,1,1,6,1,1,1,3,2,2,3,1,1,2,1,2,1,1,2,1,4,2,2,1,1,5,1,2,1,1,1,1,1,1,1,1,2,4,2,1,1,4,1,2,3,2,8,1,2,2,1,2,1,9,1,6,1,1,1,3,3,1,2,1,1,2,1,13,2,1,1,2,6,1,2,1,1,3,1,1,3,2,5,1,13,7,1,1,1,7,4,2,3,4,1,3,1,2]|256|
|[0,1,1,2,18,1]|4|
|[0,64]|64|
|[21,1,1,1,15,11]|13|
|[5,2,9,1,2,2,1,1,1,15]|21|
|[1,1,7,1,1,2,2,1,2,2]|7|
|[0,5,2,9,1,2]|16|
