### ISSUE TITLE
Panic on visor v0.7.1

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#589]
### Describe the bug:

Running visor v0.7.1 with all tasks enabled on a watch job with confidence: 5 exporting to DB storage. I was seeing this occur frequently and assumed memory pressure had been causing this. After migrating this to its own instance (to avoid contending with other deployments), I caught a full trace in the logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2345868]

goroutine 244903 [running]:
go.opentelemetry.io/otel/sdk/trace.(*evictedQueue).add(...)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.12.0/trace/evictedqueue.go:33
go.opentelemetry.io/otel/sdk/trace.(*span).addEventWithTimestamp(0xc0d8700230, 0xc02f1d3bb7bc6af1, 0x43a7f27e38, 0x6344840, 0x3ab1e8a, 0x5, 0xc0907eec00, 0x2, 0x2)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.12.0/trace/span.go:217 +0x148
go.opentelemetry.io/otel/sdk/trace.(*span).End(0xc0d8700230, 0x0, 0x0, 0x0)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.12.0/trace/span.go:126 +0x565
panic(0x366e800, 0x6181890)
/usr/local/go/src/runtime/panic.go:971 +0x499
panic(0x366e800, 0x6181890)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
go.opentelemetry.io/otel/sdk/trace.(*evictedQueue).add(...)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.12.0/trace/evictedqueue.go:33
go.opentelemetry.io/otel/sdk/trace.(*span).addEventWithTimestamp(0xc0cb52e620, 0xc02f1d3bb7bc1270, 0x43a7f225c0, 0x6344840, 0x3ab1e8a, 0x5, 0xc0907eeb80, 0x2, 0x2)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.12.0/trace/span.go:217 +0x148
go.opentelemetry.io/otel/sdk/trace.(*span).End(0xc0cb52e620, 0x0, 0x0, 0x0)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.12.0/trace/span.go:126 +0x565
panic(0x366e800, 0x6181890)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/filecoin-project/sentinel-visor/tasks/actorstate.ExtractMinerPoSts.func2(0xc0e5093ab0, 0xc0b8bbe120, 0x4)
/go/src/github.com/filecoin-project/sentinel-visor/tasks/actorstate/miner.go:479 +0x593
github.com/filecoin-project/sentinel-visor/tasks/actorstate.ExtractMinerPoSts(0x48a2f20, 0xc2c6d90f00, 0xc0f23b3d30, 0xc0eb1723c0, 0x7f1c0c854180, 0xc002288000, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/filecoin-project/sentinel-visor/tasks/actorstate/miner.go:509 +0x4a8
github.com/filecoin-project/sentinel-visor/tasks/actorstate.StorageMinerExtractor.Extract(0x48a2f20, 0xc8522dda10, 0xc0f0ae4948, 0x16, 0xc0d9b1e2a0, 0x26, 0x0, 0xc1b0f364e0, 0xc0b8bbe120, 0x4, ...)
/go/src/github.com/filecoin-project/sentinel-visor/tasks/actorstate/miner.go:74 +0x9b3
github.com/filecoin-project/sentinel-visor/tasks/actorstate.(*Task).runActorStateExtraction(0xc0bde7cf40, 0x48a2f20, 0xc8522dd9e0, 0xc0d8eef140, 0xc121f4dc00, 0xc0df1e4e18, 0x7, 0xc0f0ae4948, 0x16, 0xc0d9b1e2a0, ...)
/go/src/github.com/filecoin-project/sentinel-visor/tasks/actorstate/task.go:179 +0x4ce
created by github.com/filecoin-project/sentinel-visor/tasks/actorstate.(*Task).ProcessActors
/go/src/github.com/filecoin-project/sentinel-visor/tasks/actorstate/task.go:94 +0x8d5
```
### Steps to Reproduce:
EDIT: panics have not occurred June 30 @ ~1:20am UTC
Intermittently reproducible, but seems to eventually occur on a regular interval in our production EKS cluster. (See @placer14 for details.)

### Visor Version: docker image `filecoin/sentinel-visor:v0.7.1` on mainnet staging

**Comment by frrist** [comment]
Are the logs that occurred around this panic available? It would be helpful to know the tipsets these panics occur at.

**Comment by placer14** [comment]
Link to logs: https://app.logz.io/#/goto/0ea05125510f9333624fb69787338d65?switchToAccountId=104138

**Comment by placer14** [comment]
> It would be helpful to know the tipsets these panics occur at.

During my search there were no obvious lines which guaranteed what visor was doing when the panic occurred. No leads for height numbers. I did see mention of a CID which was included in tipset 890795. (a very weak lead)

**Comment by frrist** [comment]
I pulled the below logs from: https://app.logz.io/#/goto/9b887075aaa7f13334a9b15af32422ad?switchToAccountId=104138

The [panic](https://app.logz.io/#/dashboard/kibana/discover/doc/logzioCustomerIndex*/logzioCustomerIndex210630_v19.account-104138?_g=()&id=wxtcW3oBcWsK_ra3w52H&type=doc&switchToAccountId=104138) occurred between these timestamps

{"level":"info","ts":"2021-06-30T05:21:40.218Z","logger":"visor/chain","caller":"chain/indexer.go:321","msg":"task report","height":890797,"task":"actorstatesminer","status":"OK","time":34.251854065}

/* here be the panic */

{"level":"info","ts":"2021-06-30T05:20:38.708Z","logger":"visor/chain","caller":"chain/indexer.go:321","msg":"task report","height":890795,"task":"actorstatesminer","status":"OK","time":32.605427167}

I'd be willing to guess that this panic can be reproduced by processing tipset at height 890796

**Comment by frrist** [comment]
Somewhat interesting [log](https://app.logz.io/#/dashboard/kibana/doc/logzioCustomerIndex*/logzioCustomerIndex210630_v19.account-104138/doc/?_g=()&id=wx5dW3oBcWsK_ra3DMfL&accountIds=104138&switchToAccountId=104138) around this same time

```
child tipset ({bafy2bzacedj5teypxjojdemsoftac3k6glfwuod4hndld2xst2vsfd6m3lkjy,bafy2bzacecx6ow5teutqbcqg6fyrjypssm4ihhvvzdhc6dezkppettjweaqom,bafy2bzacedftq44y6bpw7ojezk6sscfvguvt6ywyeyvppzmfy725lopciaapc}) is not on the same chain as parent ({bafy2bzacearvls7ekwn35eu746smsedcfdlnbyemryiqdmd7yj4garunr3fee,bafy2bzacea3a5s5nostryad5syped6jzhdnnzudl5o7pklupb4otcetq6zasq,bafy2bzaceduslp3twkrpnov4gjn6cjea3bwvzugpg3ixfenastslc6nbx4r4g,bafy2bzacedkdgog3dxhms5cfccpyeyvnxbql3mjh7a73hoddtp4va7d6tefd4,bafy2bzaceb3xmgd2zetwh5jzqrmudptau4qghrlu7wyzix5xcz5cmuqwa2tek,bafy2bzacece3x55tgpuvpvigws6ajmsmcyd7pedaqe6pya3ixkjplwxtwsq66,bafy2bzacecnu3rm4mse2qb6rrtydryrsyhjbfqpfdexexhvdyyytvolwdzvr4,bafy2bzaceasjipiqn77fnau36y7wev3kwlkz7op7eyon6qnkvh5q645akct7g}):
    github.com/filecoin-project/sentinel-visor/lens/util.GetExecutedAndBlockMessagesForTipset
        /go/src/github.com/filecoin-project/sentinel-visor/lens/util/repo.go:251
```

TipSets in log: 
|TipSet|Height|
|--------|---------|
|`bafy2bzacedj5teypxjojdemsoftac3k6glfwuod4hndld2xst2vsfd6m3lkjy,bafy2bzacecx6ow5teutqbcqg6fyrjypssm4ihhvvzdhc6dezkppettjweaqom,bafy2bzacedftq44y6bpw7ojezk6sscfvguvt6ywyeyvppzmfy725lopciaapc`|     890797 |
| bafy2bzacearvls7ekwn35eu746smsedcfdlnbyemryiqdmd7yj4garunr3fee,bafy2bzacea3a5s5nostryad5syped6jzhdnnzudl5o7pklupb4otcetq6zasq,bafy2bzaceduslp3twkrpnov4gjn6cjea3bwvzugpg3ixfenastslc6nbx4r4g,bafy2bzacedkdgog3dxhms5cfccpyeyvnxbql3mjh7a73hoddtp4va7d6tefd4,bafy2bzaceb3xmgd2zetwh5jzqrmudptau4qghrlu7wyzix5xcz5cmuqwa2tek,bafy2bzacece3x55tgpuvpvigws6ajmsmcyd7pedaqe6pya3ixkjplwxtwsq66,bafy2bzacecnu3rm4mse2qb6rrtydryrsyhjbfqpfdexexhvdyyytvolwdzvr4,bafy2bzaceasjipiqn77fnau36y7wev3kwlkz7op7eyon6qnkvh5q645akct7g |     890795 |

Its possible that the chain (at least visors view of it) could have been in a wonky state at this time given the node was starting up.

**Comment by placer14** [comment]
It seems a deployment in our EKS environment is sufficient to induce the panic. Volume is less, but seemingly repeatable. Here are those logs: https://app.logz.io/#/goto/26e8a34b2968f477ac8b7a0263e28e69?switchToAccountId=104138

**Comment by placer14** [comment]
Some thoughts from chat:
@frrist
Is the watch operation running while the daemon is importing the snapshot?

@placer14 1 minute ago
Import should not be happening. (I understand there's a file semaphore which blocks it from happening more than the first successful time.) It very well may be syncing though. Typically a deployment means some blocks have generated since the repo was last saved, so maybe there's something to that? In fact, last night's deployments were higher in volume and the sync delta was also larger. Here the delta and volume were both smaller....some correlation there.

**Comment by frrist** [comment]
I would be interested in seeing:
1. Does this panic still happen if we wait for the node to catch up before starting the watch command (e.g. visor sync wait && visor watch --blahblahblah)
2. Does this panic still happen with a higher confidence. The EC2 instance has a confidence level of 100, this deployment has a confidence level of 5. A lower confidence level will cause processing to see more reorg changes.
