### ISSUE TITLE
Market deal proposals written with wrong height

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#612]
### Describe the bug:

We noticed some duplicate deals in our `market_deal_proposals` table at heights 879579 and 879580. It looks as though all the rows for height 879579 are exactly duplicated at height 879580. There may be other occurrences but checking nearby heights didn't reveal any so this is not a continuous failure. There appear to be no reorgs or forks at this time.

The `visor_processing_reports` table indicates that there were two jobs inserting data into this table: a lily watch and an offline backfill. The raw backfill data looks correct.

It looks like the watch job somehow inserted market actor data from height 879579 at height 879580.

```
 height |     reporter     |          started_at           
--------+------------------+-------------------------------
 879578 | visor            | 2021-06-27 23:41:45.176+00
 879578 | watch_1624636796 | 2021-06-26 08:39:10.693767+00
 879579 | visor            | 2021-06-27 23:41:26.436+00
 879580 | visor            | 2021-06-27 23:41:05.034+00
 879580 | watch_1624636796 | 2021-06-26 08:40:05.685355+00
 879581 | visor            | 2021-06-27 23:40:44.423+00
 879581 | watch_1624636796 | 2021-06-26 08:40:39.669726+00
 879582 | visor            | 2021-06-27 23:40:21.971+00
 879582 | watch_1624636796 | 2021-06-26 08:41:10.160323+00
 879583 | visor            | 2021-06-27 23:39:58.121+00
 879584 | visor            | 2021-06-27 23:39:41.212+00
 879584 | watch_1624636796 | 2021-06-26 08:42:05.415787+00
 879585 | visor            | 2021-06-27 23:39:19.042+00
 879585 | watch_1624636796 | 2021-06-26 08:42:40.068941+00
```

No market actor data (or any other task) was written by the watch for height 879579

A possible theory: the watch skipped that epoch and took a diff between the state at height 879578 and 879580 which resulted in the exact same set of changes but the watch records them at a different height.

I think this data was written before we added explicit SKIP statuses to `visor_processing_reports`.

**Comment by frrist** [comment]
I'm not sure what action can be taken here wrt changes in Visor. It sounds like this _was_ a bug, but we have fixed it in https://github.com/filecoin-project/sentinel-visor/commit/2dd80292c1612c2a082d9a91653c762d788d5512. Seems like the next step is to backfill the database with the fixed version of Visor.

**Comment by iand** [comment]
Pretty sure this is the cause so I will close for now and we can re-open if the problem returns.
