### ISSUE TITLE
API to reflect node is operationally ready

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#634]
Context: This work supports https://github.com/filecoin-project/helm-charts/issues/103.

### Description

As a visor operator, I would like to know when the node is in a `ready` state for the Jobs it is configured to perform. This is useful for automated deployments to reflect on the ability of the instance to act on tasks requested of it. Specifically, this should completely close the remaining downtime gap for deployments, open the door to support finer-grained failover handling, and allow other interesting programmatic handling requiring this type of reflection.

The ultimate goal of being operationally `ready` is have an endpoint which returns a bool when every job visor is performing is actively able to write to the DB. I realize there's a lot of nuance here so I will try to clarify all of the cases which constitute being `ready`:

### Acceptance criteria

When visor...
(A): is running in a daemonized mode 
~AND (B): is synced with the network~ (note: this would create infra cycling if there were a network halt or connectivity issues for our cluster. Maybe some sort of external network consensus service?)
AND (C): has zero or more completed/errored jobs (completed/errored jobs have no impact on being `ready`),
...it is `ready`.

Assuming Visor is (A)+~(B)~+(C) AND optionally...
(D): has zero active jobs
AND/OR (E): has any number of `walk` jobs
AND/OR (F): has any number of `watch` jobs whose cache is full (note: a single `watch` whose cache is not full, would make the response `notReady`)
...it is `ready`.

Assuming Visor is (A)+(B)+(C) AND optionally...
(G): has some "other behavior" which gates writing to the DB 
...the "other behavior" should also gate the API response as being `ready` (or not).

Discussion and Assumptions:

1. ~(to be considered) Given that `--to` default is `UintMax64`, any `walk` job whose `--to` is greater than chain's `<currentHeight>` should not cause that job to reflect as `notReady` as it will perform to completion what it can.~ Default `--to` is `<currentHeight>`. Was looking at old help text output. 🤝 
2. If cache reverts to a chain branch which does not completely refill the cache, the job should reflect as `notReady`.

Proposed RPC API endpoint should respond with `{ "ready": true }` and HTTP `200 OK` for `ready` or `{ "ready": false }` and HTTP `503 Not Available` for `notReady`.

### Where to begin

Plumbing from `Watcher.IsReady() bool` and `Walk.IsReady() bool` (always `true`) (both satisfying the `Job.IsReady() bool` interface), through `Scheduler.IsReady() bool`, and out from `LilyNodeAPI.LilyReady(context.Context) error` (satifying the `LilyAPI.LilyReady(ctx) error` interface).

**Comment by iand** [comment]
> Context: This work supports [filecoin-project/helm-charts#103](https://github.com/filecoin-project/helm-charts/issues/103).

Note that what you are describing here deviates from what is needed for a Kubernetes readiness probe (if that is what you are planning to use - it's not clear from the issue). Is it more of a liveness probe use case?

> 
> ### Description
> As a visor operator, I would like to know when the node is in a `ready` state for the Jobs it is configured to perform. This is useful for automated deployments to reflect on the ability of the instance to act on tasks requested of it. Specifically, this should completely close the remaining downtime gap for deployments, open the door to support finer-grained failover handling, and allow other interesting programmatic handling requiring this type of reflection.
> 
> The ultimate goal of being operationally `ready` is have an endpoint which returns a bool when every job visor is performing is actively able to write to the DB. I realize there's a lot of nuance here so I will try to clarify all of the cases which constitute being `ready`:

Can a node flip between `Ready` and `NotReady` or is `Ready` a terminal state?

What is the state machine? 

> 
> ### Acceptance criteria
> When visor...
> (A): is running in a daemonized mode
> AND (B): is synced with the network
> AND (C): has zero or more completed/errored jobs (completed/errored jobs have no impact on being `ready`),
> ...it is `ready`.

Does adding a new job cause the node to become `NotReady`?

Does falling behind the chain by one epoch cause the node to become `NotReady`?

> 
> Assuming Visor is (A)+(B)+(C) AND optionally...
> (D): has zero active jobs
> AND/OR (E): has any number of `walk` jobs
> AND/OR (F): has any number of `watch` jobs whose cache is full (note: a single `watch` whose cache is not full, would make the response `notReady`)

This implies that an analysis node will not become `Ready` for 3000 seconds which seems like a very long time to wait. Are we going to be taking actions such as alerting or failover on this?

> ...it is `ready`.
> 
> Assuming Visor is (A)+(B)+(C) AND optionally...
> (G): has some "other behavior" which gates writing to the DB
> ...the "other behavior" should also gate the API response as being `ready` (or not).
> 
> Discussion and Assumptions:
> 
> 1. (to be considered) Given that `--to` default is `UintMax64`, any `walk` job whose `--to` is greater than chain's `<currentHeight>` should not cause that job to reflect as `notReady` as it will perform to completion what it can.

Default `--to` for walk is current epoch.

> 2. If cache reverts to a chain branch which does not completely refill the cache, the job should reflect as `notReady`.

If this happens should the node flip from `Ready` to `NotReady`?

> 
> Proposed RPC API endpoint should respond with `{ "ready": true }` for `ready` or `{ "ready": false }` for `notReady`.
> 

What's the proposed name of the RPC API? 

What is the command name that will query it?

> ### Where to begin
> Plumbing from `Watcher.IsReady() bool` and `Walk.IsReady() bool` (always `true`) (both satisfying the `Job.IsReady() bool` interface), through `Scheduler.IsReady() bool`, and out from `LilyNodeAPI.LilyReady(context.Context) error` (satifying the `LilyAPI.LilyReady(ctx) error` interface).

**Comment by iand** [comment]
@mg here's a suggestion. We currently have a the `visor wait-api` command that waits for the API to come online. We could expand this into a general wait command:
 
 - `visor wait api` - waits for the API to become ready
 - `visor wait sync` - waits for network to be fully synced (alias or improved version of `visor sync wait`)
 - `visor wait job --event=start --all` - waits for all jobs to start
 - `visor wait job ---event=start --id=xxx` - waits for job with id xxx to start
 - `visor wait job --event=stop --all` - waits for all jobs to complete (even if they had errors)
 - `visor wait job --event=stop --id=xxx` - waits for job with id xxx to complete 

All of these commands would have the same behaviour: block until the condition is reached and then exit with code 0.

cc @frrist

**Comment by frrist** [comment]
One way this API will be used is to ensure data from a new deployment is being written to Storage before taking down an older deployment. An outcome of this will be fewer (zero?) gaps in our data when upgrading to new a version of Visor. Is that right? 

(assuming the above is true)

I would expect a transition from `notReady` to `ready` to occur once all tasks have been successfully processed and written to storage for the first time in a job. I would also expect `ready` to be a terminal state - I think this simplifies things a great deal wrt to flapping readiness.

**Comment by placer14** [comment]
> An outcome of this will be fewer (zero?) gaps in our data when upgrading to new a version of Visor. Is that right?

Yes, exactly...

> Note that how what you are describing here deviates from what is needed for a Kubernetes readiness probe (if that is what you are planning to use - it's not clear from the issue). Is it more of a liveness probe use case?

I now realize how `ready`|`notReady` is misleading. I intend to use this for a liveness check such that it can be cycled when the node stops writing for a period of time, but more importantly, it can gate the teardown of another live deployment (which currently only gates the teardown when the new deploy is ready (but internally, is still warming cache and not writing to the DB)).

> Can a node flip between Ready and NotReady or is Ready a terminal state? What is the state machine?

```
(roughly)

     start
       │
       │
       │
       ▼    ─────────►
     notReady        ready
       │    ◄───────── │
       │               │
       │               │
       ▼               │
      end  ◄───────────┘

```

I _assume_ ready state to be relatively stable during a 30s period since most of the changes hinge on the cache state (which only changes significantly during reorgs?). The liveness probe can have a tolerance for flapping using higher `failureThreshold` w a shorter check interval. The goal being to tolerate a reorg which interrupts, say, 1-`n` (for some small `n`) epochs of recovery, but to failover to standby for anything much longer.

> I would expect a transition from notReady to ready to occur once all tasks have been successfully processed and written to storage for the first time in a job. I would also expect ready to be a terminal state - I think this simplifies things a great deal wrt to flapping readiness.

I think our `job` CLI would make a liar out of "`ready` being a terminal state" given that you can async add jobs which would cause the node to be `notReady` given the rules above. I think it would be more-correct for the node to be honest and let the consumer to reflect/react via the API using the latest/most-accurate state data.

> Does adding a new job cause the node to become NotReady?

For simplicity in initial design, yes. If we have `replicaCount = 2`, I expect a job update to be deploy event which gets applied to the standby first. Once standby reports live, then jobs can be removed on the main and moved into the standby slot (or recreated for other updates to be applied). (I may want to explore hot-applying a config of jobs to a daemonized node without restarting it at some point.)

> Does falling behind the chain by one epoch cause the node to become NotReady?

I recommend a parameterized tolerance for chain head lag WRT readiness. I would expect visor to be at least 10s behind due to network propagation/latency anyway and allowing `m = 1`(?) epochs of lag would probably be warranted.

I think the real problem comes from detecting/handling null rounds or if the network halts. We don't want Sentinel cycling during legit chain halt events. Which probably requires some service constantly polling multiple points for their state and reporting on consensus health. Which kinda blows this scope into a larger magnitude. Perhaps we relax the chain sync requirement until we figure this part out.

> This implies that an analysis node will not become Ready for 3000 seconds which seems like a very long time to wait. Are we going to be taking actions such as alerting or failover on this?

This is already the case and what we're trying to prevent. Ideally, when we're changing/adding an analysis deployment, we bring up the new node with the desired changes, wait 3000~ seconds for it to be ready, then teardown/update/whatever to the old node. Ideally, there is a clean handoff (even some overlap as far as data is concerned).

> Default `--to` for walk is current epoch.

Thanks, was looking at an old visor help text. I see it's updated now. 👍 

> > If cache reverts to a chain branch which does not completely refill the cache, the job should reflect as notReady.
> If this happens should the node flip from Ready to NotReady?

Yes. I expect this to be temporarily `notReady` but then be `ready` once it's recovered.

**Comment by placer14** [comment]
I love the idea to combine into a more robust `wait` CLI API. But K8s will probably be using an HTTP request to confirm though. (I've added HTTP status codes to the requirements, which is what the probes base their check on.)

I expect the HTTP RPC request to be under the namespace of the rest of the `LilyJob` endpoints (assuming they have an RPC equiv). It looks like we just adopt the existing `Filecoin` namespace for RPC calls and maybe there are no lily-specific RPC handlers? In which case, this would be the first and I'd probably fall toward something like `Debug.LilyStatus`?

**Comment by frrist** [comment]
This is starting to sound like a couple of different things.
- Something that returns `read` or `notready` for gating when to take down an old deployment.
- Something that returns `caught-up` or `behind` for detecting when job(s) have a full cache or partially full/empty cache.

**Comment by placer14** [comment]
For deployment purposes, the main two mechanisms I intend to use is the startup and readiness probes:
- startup probe (which I will use `wait-api` for) that tells k8s when to start readiness checks
- readiness probes (which is the scope covered here) which tells k8s when the deployment is ready/operational

For simplicity, we decided that the readiness probe will simply wait for first DB write for all tasks. Once all tasks have written some bytes, this probe check will return `ready` and will be a terminal state. (Returning `notReady` up until this point.)

The responsibility of knowing when the node is unhealthy is likely going to be the responsibility of some external watchdog which can reason about the state of many nodes or other sources of truth. (Given that decentralized nodes rely on consensus to be "healthy" or not, it requires being aware of some externalities which one visor alone should not be responsible for.) Closing this issue discussion as resolved and will open new issues w the separate scopes born out of this.

**Comment by placer14** [comment]
Simplified scope for readiness probe: https://github.com/filecoin-project/sentinel-visor/issues/641
