### ISSUE TITLE
Guarding multiple csv extracts to the same location 

### ISSUE THREAD

**Issue by thattommyhall** [filecoin-project/sentinel-visor#637]
### Description

I think at the moment we get mangled csv's if we run concurrent walks in the same folder, I was thinking it might be easy enough to take a lock on the file and exit if the lock cannot be taken to guard against this

### Acceptance criteria

Cannot run 2 walks to the same csv files concurrently

**Comment by iand** [comment]
This is fixed by https://github.com/filecoin-project/sentinel-visor/pull/622 but only for lily jobs. We could port to `visor run walk` but I'm not sure it's worth doing since we are aiming to deprecate the run command.
